:: The beta and beta/sigma reductions of lambda_EnvEps

::  The three beta computation rules are given once, as BetaRoot(V); the beta
::  reduction is their compatible closure, and the beta/sigma reduction is the
::  compatible closure of the union of the beta and sigma rules.  That the
::  latter is the union of the two reductions is then a theorem, not a
::  definition.

environ

 vocabularies NUMBERS, XBOOLE_0, SUBSET_1, TARSKI, ZFMISC_1, FINSEQ_1,
      RELAT_1, FUNCT_1, ORDINAL1, CARD_1, ARYTM_3, XXREAL_0, NAT_1, TREES_1,
      TREES_2, TREES_3, TREES_4, LANG1, STRUCT_0, DTCONSTR, MCART_1, XTUPLE_0,
      FINSET_1, TDGROUP, FUNCOP_1, ARYTM_1, FUNCT_7, XREAL_0, XCMPLX_0,
      REWRITE1, PBOOLE, ENVSYN, ENVCC, ENVSIG, ENVBETA;
 notations TARSKI, XBOOLE_0, ZFMISC_1, SUBSET_1, ORDINAL1, NUMBERS, XCMPLX_0,
      XXREAL_0, NAT_1, RELAT_1, RELSET_1, FUNCT_1, FUNCT_2, FINSEQ_1, FINSEQ_2,
      MCART_1, XTUPLE_0, DOMAIN_1, STRUCT_0, LANG1, TREES_1, TREES_2, TREES_3,
      TREES_4, DTCONSTR, FUNCOP_1, XREAL_0, PBOOLE, REWRITE1, ENVSYN, ENVCC,
      ENVSIG;
 constructors NUMBERS, XCMPLX_0, XXREAL_0, NAT_1, RELSET_1, FUNCT_2, FINSEQ_1,
      FINSEQ_2, MCART_1, XTUPLE_0, DOMAIN_1, STRUCT_0, LANG1, TREES_1, TREES_2,
      TREES_3, TREES_4, DTCONSTR, PARTFUN1, BINOP_1, SETWISEO, XREAL_0,
      FUNCOP_1, SUBSET_1, CARD_3, FINSEQOP, FINSEQ_4, FINSOP_1, PRE_POLY,
      FUNCT_1, RELAT_1, PBOOLE, REWRITE1, ENVSYN, ENVCC, ENVSIG;
 registrations XBOOLE_0, SUBSET_1, RELAT_1, FUNCT_1, ORDINAL1, XREAL_0, NAT_1,
      FINSEQ_1, FINSEQ_2, FINSET_1, CARD_1, STRUCT_0, LANG1, TREES_1, TREES_2,
      TREES_3, TREES_4, DTCONSTR, XTUPLE_0, VALUED_0, FUNCOP_1, XCMPLX_0,
      XXREAL_0, NUMBERS, MEMBERED, PBOOLE, REWRITE1, ENVSYN;
 requirements NUMERALS, REAL, BOOLE, SUBSET, ARITHM;
 definitions TARSKI, XBOOLE_0, RELAT_1, SUBSET_1, REWRITE1, ENVSYN, ENVCC,
      ENVSIG;
 theorems TARSKI, XBOOLE_0, XBOOLE_1, ZFMISC_1, XTUPLE_0, RELAT_1, REWRITE1,
      ENVSYN, ENVCC, ENVSIG;
 schemes NAT_1;

begin :: The three computation rules of the beta reduction

reserve V for non empty set;

definition
  let V be non empty set;
  func BetaRoot(V) -> EnvEpsRel of V equals
  :Def1:
  { z where z is Element of [:TS(EnvEpsGram(V)),TS(EnvEpsGram(V)):] :
      ex P,S being EnvEpsTerm of V st z = [P,S] &
      (
        ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
            P = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) ) or
        ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
            P = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) ) or
        ( ex A,B being EnvEpsTerm of V st
            P = (eEps A) (@) B & S = A (o) B ) ) };
  coherence
  proof
    set G = EnvEpsGram(V);
    set D = [:TS G, TS G:];
    set S0 = { z where z is Element of D :
      ex P,S being EnvEpsTerm of V st z = [P,S] &
      (
        ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
            P = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) ) or
        ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
            P = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) ) or
        ( ex A,B being EnvEpsTerm of V st
            P = (eEps A) (@) B & S = A (o) B ) ) };
    S0 c= D
    proof
      let u be object;
      assume u in S0;
      then ex z being Element of D st u = z &
        ex P,S being EnvEpsTerm of V st z = [P,S] &
        (
          ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
              P = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) ) or
          ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
              P = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) ) or
          ( ex A,B being EnvEpsTerm of V st
              P = (eEps A) (@) B & S = A (o) B ) );
      hence thesis;
    end;
    hence thesis;
  end;
end;

theorem Th1:
  for V being non empty set, P,S being EnvEpsTerm of V holds
  ( [P,S] in BetaRoot(V) iff
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        P = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) ) or
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        P = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) ) or
    ( ex A,B being EnvEpsTerm of V st
        P = (eEps A) (@) B & S = A (o) B ) )
proof
  let V be non empty set, P,S be EnvEpsTerm of V;
  set G = EnvEpsGram(V);
  set D = [:TS G, TS G:];
  A0: [P,S] in D by ZFMISC_1:87;
  hereby
    assume [P,S] in BetaRoot(V);
    then [P,S] in { z where z is Element of D :
      ex P2,S2 being EnvEpsTerm of V st z = [P2,S2] &
      (
        ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
            P2 = eLam(x0,A) (@) B & S2 = A (o) eExt(B,x0,eId V) ) or
        ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
            P2 = (eLam(x0,A) (o) C) (@) B & S2 = A (o) eExt(B,x0,C) ) or
        ( ex A,B being EnvEpsTerm of V st
            P2 = (eEps A) (@) B & S2 = A (o) B ) ) } by Def1;
    then consider z being Element of D such that
    B1: [P,S] = z and
    B2:
      ex P2,S2 being EnvEpsTerm of V st z = [P2,S2] &
      (
        ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
            P2 = eLam(x0,A) (@) B & S2 = A (o) eExt(B,x0,eId V) ) or
        ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
            P2 = (eLam(x0,A) (o) C) (@) B & S2 = A (o) eExt(B,x0,C) ) or
        ( ex A,B being EnvEpsTerm of V st
            P2 = (eEps A) (@) B & S2 = A (o) B ) );
    consider P2,S2 being EnvEpsTerm of V such that
    B3: z = [P2,S2] &
    (
      ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
          P2 = eLam(x0,A) (@) B & S2 = A (o) eExt(B,x0,eId V) ) or
      ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
          P2 = (eLam(x0,A) (o) C) (@) B & S2 = A (o) eExt(B,x0,C) ) or
      ( ex A,B being EnvEpsTerm of V st
          P2 = (eEps A) (@) B & S2 = A (o) B ) ) by B2;
    B4: P = P2 & S = S2 by B1,B3,XTUPLE_0:1;
    thus
      ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
          P = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) ) or
      ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
          P = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) ) or
      ( ex A,B being EnvEpsTerm of V st
          P = (eEps A) (@) B & S = A (o) B ) by B3,B4;
  end;
  assume C1:
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        P = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) ) or
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        P = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) ) or
    ( ex A,B being EnvEpsTerm of V st
        P = (eEps A) (@) B & S = A (o) B );
  reconsider z = [P,S] as Element of D by A0;
  C2:
    ex P2,S2 being EnvEpsTerm of V st z = [P2,S2] &
    (
      ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
          P2 = eLam(x0,A) (@) B & S2 = A (o) eExt(B,x0,eId V) ) or
      ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
          P2 = (eLam(x0,A) (o) C) (@) B & S2 = A (o) eExt(B,x0,C) ) or
      ( ex A,B being EnvEpsTerm of V st
          P2 = (eEps A) (@) B & S2 = A (o) B ) ) by C1;
  z in { z2 where z2 is Element of D :
      ex P2,S2 being EnvEpsTerm of V st z2 = [P2,S2] &
      (
        ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
            P2 = eLam(x0,A) (@) B & S2 = A (o) eExt(B,x0,eId V) ) or
        ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
            P2 = (eLam(x0,A) (o) C) (@) B & S2 = A (o) eExt(B,x0,C) ) or
        ( ex A,B being EnvEpsTerm of V st
            P2 = (eEps A) (@) B & S2 = A (o) B ) ) } by C2;
  hence thesis by Def1;
end;

:: beta
theorem Th2:
  for V being non empty set, M,N being EnvEpsTerm of V, x being Element of V
    holds
  [eLam(x,M) (@) N, M (o) eExt(N,x,eId V)] in BetaRoot(V)
proof
  let V be non empty set, M,N be EnvEpsTerm of V, x be Element of V;
  A1: ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
      eLam(x,M) (@) N = eLam(x0,A) (@) B & M (o) eExt(N,x,eId V) = A (o)
      eExt(B,x0,eId V) )
  proof
    take M,N,x;
    thus thesis;
  end;
  thus thesis by A1,Th1;
end;

:: betaClos
theorem Th3:
  for V being non empty set, M,N,L being EnvEpsTerm of V, x being Element of
    V holds
  [(eLam(x,M) (o) L) (@) N, M (o) eExt(N,x,L)] in BetaRoot(V)
proof
  let V be non empty set, M,N,L be EnvEpsTerm of V, x be Element of V;
  A1: ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
      (eLam(x,M) (o) L) (@) N = (eLam(x0,A) (o) C) (@) B & M (o) eExt(N,x,L)
      = A (o) eExt(B,x0,C) )
  proof
    take M,N,L,x;
    thus thesis;
  end;
  thus thesis by A1,Th1;
end;

:: compEps
theorem Th4:
  for V being non empty set, M,N being EnvEpsTerm of V holds
  [(eEps M) (@) N, M (o) N] in BetaRoot(V)
proof
  let V be non empty set, M,N be EnvEpsTerm of V;
  A1: ( ex A,B being EnvEpsTerm of V st
      (eEps M) (@) N = (eEps A) (@) B & M (o) N = A (o) B )
  proof
    take M,N;
    thus thesis;
  end;
  thus thesis by A1,Th1;
end;

begin :: The beta reduction

definition
  let V be non empty set;
  func BetaRed(V) -> EnvEpsRel of V equals
  :Def2:
  CC BetaRoot(V);
  coherence;
end;

begin :: The eleven rules of the beta reduction

:: beta
theorem Th5:
  for V being non empty set, M,N being EnvEpsTerm of V, x being Element of V
    holds
  [eLam(x,M) (@) N, M (o) eExt(N,x,eId V)] in BetaRed(V)
proof
  let V be non empty set, M,N be EnvEpsTerm of V, x be Element of V;
  A1: [eLam(x,M) (@) N, M (o) eExt(N,x,eId V)] in BetaRoot(V) by Th2;
  BetaRoot(V) c= CC BetaRoot(V) by ENVCC:4;
  hence thesis by A1,Def2;
end;

:: betaClos
theorem Th6:
  for V being non empty set, M,N,L being EnvEpsTerm of V, x being Element of
    V holds
  [(eLam(x,M) (o) L) (@) N, M (o) eExt(N,x,L)] in BetaRed(V)
proof
  let V be non empty set, M,N,L be EnvEpsTerm of V, x be Element of V;
  A1: [(eLam(x,M) (o) L) (@) N, M (o) eExt(N,x,L)] in BetaRoot(V) by Th3;
  BetaRoot(V) c= CC BetaRoot(V) by ENVCC:4;
  hence thesis by A1,Def2;
end;

:: compEps
theorem Th7:
  for V being non empty set, M,N being EnvEpsTerm of V holds
  [(eEps M) (@) N, M (o) N] in BetaRed(V)
proof
  let V be non empty set, M,N be EnvEpsTerm of V;
  A1: [(eEps M) (@) N, M (o) N] in BetaRoot(V) by Th4;
  BetaRoot(V) c= CC BetaRoot(V) by ENVCC:4;
  hence thesis by A1,Def2;
end;

theorem Th8:
  for V being non empty set, M,M1,N being EnvEpsTerm of V st [M,M1] in
    BetaRed(V) holds
  [M (@) N, M1 (@) N] in BetaRed(V)
proof
  let V be non empty set, M,M1,N be EnvEpsTerm of V;
  assume [M,M1] in BetaRed(V);
  then [M,M1] in CC BetaRoot(V) by Def2;
  then [M (@) N, M1 (@) N] in CC BetaRoot(V) by ENVCC:5;
  hence thesis by Def2;
end;

theorem Th9:
  for V being non empty set, M,N,N1 being EnvEpsTerm of V st [N,N1] in
    BetaRed(V) holds
  [M (@) N, M (@) N1] in BetaRed(V)
proof
  let V be non empty set, M,N,N1 be EnvEpsTerm of V;
  assume [N,N1] in BetaRed(V);
  then [N,N1] in CC BetaRoot(V) by Def2;
  then [M (@) N, M (@) N1] in CC BetaRoot(V) by ENVCC:6;
  hence thesis by Def2;
end;

theorem Th10:
  for V being non empty set, M,M1 being EnvEpsTerm of V, x being Element of
    V st [M,M1] in BetaRed(V) holds
  [eLam(x,M), eLam(x,M1)] in BetaRed(V)
proof
  let V be non empty set, M,M1 be EnvEpsTerm of V, x be Element of V;
  assume [M,M1] in BetaRed(V);
  then [M,M1] in CC BetaRoot(V) by Def2;
  then [eLam(x,M), eLam(x,M1)] in CC BetaRoot(V) by ENVCC:7;
  hence thesis by Def2;
end;

theorem Th11:
  for V being non empty set, M,M1,N being EnvEpsTerm of V, x being Element
    of V st [M,M1] in BetaRed(V) holds
  [eExt(M,x,N), eExt(M1,x,N)] in BetaRed(V)
proof
  let V be non empty set, M,M1,N be EnvEpsTerm of V, x be Element of V;
  assume [M,M1] in BetaRed(V);
  then [M,M1] in CC BetaRoot(V) by Def2;
  then [eExt(M,x,N), eExt(M1,x,N)] in CC BetaRoot(V) by ENVCC:8;
  hence thesis by Def2;
end;

theorem Th12:
  for V being non empty set, M,N,N1 being EnvEpsTerm of V, x being Element
    of V st [N,N1] in BetaRed(V) holds
  [eExt(M,x,N), eExt(M,x,N1)] in BetaRed(V)
proof
  let V be non empty set, M,N,N1 be EnvEpsTerm of V, x be Element of V;
  assume [N,N1] in BetaRed(V);
  then [N,N1] in CC BetaRoot(V) by Def2;
  then [eExt(M,x,N), eExt(M,x,N1)] in CC BetaRoot(V) by ENVCC:9;
  hence thesis by Def2;
end;

theorem Th13:
  for V being non empty set, M,M1,N being EnvEpsTerm of V st [M,M1] in
    BetaRed(V) holds
  [M (o) N, M1 (o) N] in BetaRed(V)
proof
  let V be non empty set, M,M1,N be EnvEpsTerm of V;
  assume [M,M1] in BetaRed(V);
  then [M,M1] in CC BetaRoot(V) by Def2;
  then [M (o) N, M1 (o) N] in CC BetaRoot(V) by ENVCC:10;
  hence thesis by Def2;
end;

theorem Th14:
  for V being non empty set, M,N,N1 being EnvEpsTerm of V st [N,N1] in
    BetaRed(V) holds
  [M (o) N, M (o) N1] in BetaRed(V)
proof
  let V be non empty set, M,N,N1 be EnvEpsTerm of V;
  assume [N,N1] in BetaRed(V);
  then [N,N1] in CC BetaRoot(V) by Def2;
  then [M (o) N, M (o) N1] in CC BetaRoot(V) by ENVCC:11;
  hence thesis by Def2;
end;

theorem Th15:
  for V being non empty set, M,M1 being EnvEpsTerm of V st [M,M1] in
    BetaRed(V) holds
  [eEps M, eEps M1] in BetaRed(V)
proof
  let V be non empty set, M,M1 be EnvEpsTerm of V;
  assume [M,M1] in BetaRed(V);
  then [M,M1] in CC BetaRoot(V) by Def2;
  then [eEps M, eEps M1] in CC BetaRoot(V) by ENVCC:12;
  hence thesis by Def2;
end;

begin :: Inversion

theorem Th16:
  for V being non empty set, P,S being EnvEpsTerm of V
  st [P,S] in BetaRed(V) holds
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        P = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) ) or
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        P = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) ) or
    ( ex A,B being EnvEpsTerm of V st
        P = (eEps A) (@) B & S = A (o) B ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        P = A (@) B & S = A1 (@) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        P = A (@) B & S = A (@) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        P = eLam(x0,A) & S = eLam(x0,A1) ) or
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        P = eExt(A,x0,B) & S = eExt(A1,x0,B) ) or
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        P = eExt(A,x0,B) & S = eExt(A,x0,B1) ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        P = A (o) B & S = A1 (o) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        P = A (o) B & S = A (o) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        P = eEps A & S = eEps A1 )
proof
  let V be non empty set, P,S be EnvEpsTerm of V;
  assume [P,S] in BetaRed(V);
  then A1: [P,S] in CC BetaRoot(V) by Def2;
  A2: [P,S] in BetaRoot(V) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in CC BetaRoot(V) & P = A
      (@) B & S = A1 (@) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in CC BetaRoot(V) & P = A
      (@) B & S = A (@) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in CC
      BetaRoot(V) & P = eLam(x0,A) & S = eLam(x0,A1) ) or
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in CC
      BetaRoot(V) & P = eExt(A,x0,B) & S = eExt(A1,x0,B) ) or
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in CC
      BetaRoot(V) & P = eExt(A,x0,B) & S = eExt(A,x0,B1) ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in CC BetaRoot(V) & P = A
      (o) B & S = A1 (o) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in CC BetaRoot(V) & P = A
      (o) B & S = A (o) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in CC BetaRoot(V) & P = eEps A
      & S = eEps A1 ) by A1,ENVCC:13;
  per cases by A2;
  suppose [P,S] in BetaRoot(V);
    hence thesis by Th1;
  end;
  suppose ex A,A1,B being EnvEpsTerm of V st [A,A1] in CC BetaRoot(V) & P =
    A (@) B & S = A1 (@) B;
    then consider A,A1,B being EnvEpsTerm of V such that
    B2: [A,A1] in CC BetaRoot(V) & P = A (@) B & S = A1 (@) B;
    B3: [A,A1] in BetaRed(V) by B2,Def2;
    B4: ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) & P = A
      (@) B & S = A1 (@) B )
    proof
      take A,A1,B;
      thus thesis by B2,B3;
    end;
    thus thesis by B4;
  end;
  suppose ex A,B,B1 being EnvEpsTerm of V st [B,B1] in CC BetaRoot(V) & P =
    A (@) B & S = A (@) B1;
    then consider A,B,B1 being EnvEpsTerm of V such that
    B2: [B,B1] in CC BetaRoot(V) & P = A (@) B & S = A (@) B1;
    B3: [B,B1] in BetaRed(V) by B2,Def2;
    B4: ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) & P = A
      (@) B & S = A (@) B1 )
    proof
      take A,B,B1;
      thus thesis by B2,B3;
    end;
    thus thesis by B4;
  end;
  suppose ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    CC BetaRoot(V) & P = eLam(x0,A) & S = eLam(x0,A1);
    then consider A,A1 being EnvEpsTerm of V, x0 being Element of V such
      that
    B2: [A,A1] in CC BetaRoot(V) & P = eLam(x0,A) & S = eLam(x0,A1);
    B3: [A,A1] in BetaRed(V) by B2,Def2;
    B4: ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
      BetaRed(V) & P = eLam(x0,A) & S = eLam(x0,A1) )
    proof
      take A,A1,x0;
      thus thesis by B2,B3;
    end;
    thus thesis by B4;
  end;
  suppose ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1]
    in CC BetaRoot(V) & P = eExt(A,x0,B) & S = eExt(A1,x0,B);
    then consider A,A1,B being EnvEpsTerm of V, x0 being Element of V such
      that
    B2: [A,A1] in CC BetaRoot(V) & P = eExt(A,x0,B) & S = eExt(A1,x0,B);
    B3: [A,A1] in BetaRed(V) by B2,Def2;
    B4: ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1]
      in BetaRed(V) & P = eExt(A,x0,B) & S = eExt(A1,x0,B) )
    proof
      take A,A1,B,x0;
      thus thesis by B2,B3;
    end;
    thus thesis by B4;
  end;
  suppose ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1]
    in CC BetaRoot(V) & P = eExt(A,x0,B) & S = eExt(A,x0,B1);
    then consider A,B,B1 being EnvEpsTerm of V, x0 being Element of V such
      that
    B2: [B,B1] in CC BetaRoot(V) & P = eExt(A,x0,B) & S = eExt(A,x0,B1);
    B3: [B,B1] in BetaRed(V) by B2,Def2;
    B4: ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1]
      in BetaRed(V) & P = eExt(A,x0,B) & S = eExt(A,x0,B1) )
    proof
      take A,B,B1,x0;
      thus thesis by B2,B3;
    end;
    thus thesis by B4;
  end;
  suppose ex A,A1,B being EnvEpsTerm of V st [A,A1] in CC BetaRoot(V) & P =
    A (o) B & S = A1 (o) B;
    then consider A,A1,B being EnvEpsTerm of V such that
    B2: [A,A1] in CC BetaRoot(V) & P = A (o) B & S = A1 (o) B;
    B3: [A,A1] in BetaRed(V) by B2,Def2;
    B4: ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) & P = A
      (o) B & S = A1 (o) B )
    proof
      take A,A1,B;
      thus thesis by B2,B3;
    end;
    thus thesis by B4;
  end;
  suppose ex A,B,B1 being EnvEpsTerm of V st [B,B1] in CC BetaRoot(V) & P =
    A (o) B & S = A (o) B1;
    then consider A,B,B1 being EnvEpsTerm of V such that
    B2: [B,B1] in CC BetaRoot(V) & P = A (o) B & S = A (o) B1;
    B3: [B,B1] in BetaRed(V) by B2,Def2;
    B4: ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) & P = A
      (o) B & S = A (o) B1 )
    proof
      take A,B,B1;
      thus thesis by B2,B3;
    end;
    thus thesis by B4;
  end;
  suppose ex A,A1 being EnvEpsTerm of V st [A,A1] in CC BetaRoot(V) & P =
    eEps A & S = eEps A1;
    then consider A,A1 being EnvEpsTerm of V such that
    B2: [A,A1] in CC BetaRoot(V) & P = eEps A & S = eEps A1;
    B3: [A,A1] in BetaRed(V) by B2,Def2;
    B4: ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) & P = eEps A
      & S = eEps A1 )
    proof
      take A,A1;
      thus thesis by B2,B3;
    end;
    thus thesis by B4;
  end;
end;

begin :: Inversion by the head constructor

theorem Th17:
  for V being non empty set, x being Element of V, S being EnvEpsTerm of V
    holds
  not [eVar x,S] in BetaRed(V)
proof
  let V be non empty set, x be Element of V, S be EnvEpsTerm of V;
  assume [eVar x,S] in BetaRed(V);
  then A1:
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        eVar x = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) ) or
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        eVar x = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) ) or
    ( ex A,B being EnvEpsTerm of V st
        eVar x = (eEps A) (@) B & S = A (o) B ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eVar x = A (@) B & S = A1 (@) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eVar x = A (@) B & S = A (@) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eVar x = eLam(x0,A) & S = eLam(x0,A1) ) or
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eVar x = eExt(A,x0,B) & S = eExt(A1,x0,B) ) or
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        eVar x = eExt(A,x0,B) & S = eExt(A,x0,B1) ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eVar x = A (o) B & S = A1 (o) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eVar x = A (o) B & S = A (o) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eVar x = eEps A & S = eEps A1 ) by Th16;
  per cases by A1;
  suppose
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        eVar x = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) )
    ;
    then consider A,B being EnvEpsTerm of V, x0 being Element of V such that
    E1: eVar x = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        eVar x = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) )
    ;
    then consider A,B,C being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: eVar x = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B being EnvEpsTerm of V st
        eVar x = (eEps A) (@) B & S = A (o) B )
    ;
    then consider A,B being EnvEpsTerm of V such that
    E1: eVar x = (eEps A) (@) B & S = A (o) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eVar x = A (@) B & S = A1 (@) B )
    ;
    then consider A,A1,B being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & eVar x = A (@) B & S = A1 (@) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eVar x = A (@) B & S = A (@) B1 )
    ;
    then consider A,B,B1 being EnvEpsTerm of V such that
    E1: [B,B1] in BetaRed(V) & eVar x = A (@) B & S = A (@) B1;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eVar x = eLam(x0,A) & S = eLam(x0,A1) )
    ;
    then consider A,A1 being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [A,A1] in BetaRed(V) & eVar x = eLam(x0,A) & S = eLam(x0,A1);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eVar x = eExt(A,x0,B) & S = eExt(A1,x0,B) )
    ;
    then consider A,A1,B being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [A,A1] in BetaRed(V) & eVar x = eExt(A,x0,B) & S = eExt(A1,x0,B);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        eVar x = eExt(A,x0,B) & S = eExt(A,x0,B1) )
    ;
    then consider A,B,B1 being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [B,B1] in BetaRed(V) & eVar x = eExt(A,x0,B) & S = eExt(A,x0,B1);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eVar x = A (o) B & S = A1 (o) B )
    ;
    then consider A,A1,B being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & eVar x = A (o) B & S = A1 (o) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eVar x = A (o) B & S = A (o) B1 )
    ;
    then consider A,B,B1 being EnvEpsTerm of V such that
    E1: [B,B1] in BetaRed(V) & eVar x = A (o) B & S = A (o) B1;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eVar x = eEps A & S = eEps A1 )
    ;
    then consider A,A1 being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & eVar x = eEps A & S = eEps A1;
    thus thesis by E1,ENVSYN:20;
  end;
end;

theorem Th18:
  for V being non empty set, S being EnvEpsTerm of V holds
  not [eId V,S] in BetaRed(V)
proof
  let V be non empty set, S be EnvEpsTerm of V;
  assume [eId V,S] in BetaRed(V);
  then A1:
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        eId V = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) ) or
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        eId V = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) ) or
    ( ex A,B being EnvEpsTerm of V st
        eId V = (eEps A) (@) B & S = A (o) B ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eId V = A (@) B & S = A1 (@) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eId V = A (@) B & S = A (@) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eId V = eLam(x0,A) & S = eLam(x0,A1) ) or
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eId V = eExt(A,x0,B) & S = eExt(A1,x0,B) ) or
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        eId V = eExt(A,x0,B) & S = eExt(A,x0,B1) ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eId V = A (o) B & S = A1 (o) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eId V = A (o) B & S = A (o) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eId V = eEps A & S = eEps A1 ) by Th16;
  per cases by A1;
  suppose
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        eId V = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) )
    ;
    then consider A,B being EnvEpsTerm of V, x0 being Element of V such that
    E1: eId V = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        eId V = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) )
    ;
    then consider A,B,C being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: eId V = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B being EnvEpsTerm of V st
        eId V = (eEps A) (@) B & S = A (o) B )
    ;
    then consider A,B being EnvEpsTerm of V such that
    E1: eId V = (eEps A) (@) B & S = A (o) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eId V = A (@) B & S = A1 (@) B )
    ;
    then consider A,A1,B being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & eId V = A (@) B & S = A1 (@) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eId V = A (@) B & S = A (@) B1 )
    ;
    then consider A,B,B1 being EnvEpsTerm of V such that
    E1: [B,B1] in BetaRed(V) & eId V = A (@) B & S = A (@) B1;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eId V = eLam(x0,A) & S = eLam(x0,A1) )
    ;
    then consider A,A1 being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [A,A1] in BetaRed(V) & eId V = eLam(x0,A) & S = eLam(x0,A1);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eId V = eExt(A,x0,B) & S = eExt(A1,x0,B) )
    ;
    then consider A,A1,B being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [A,A1] in BetaRed(V) & eId V = eExt(A,x0,B) & S = eExt(A1,x0,B);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        eId V = eExt(A,x0,B) & S = eExt(A,x0,B1) )
    ;
    then consider A,B,B1 being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [B,B1] in BetaRed(V) & eId V = eExt(A,x0,B) & S = eExt(A,x0,B1);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eId V = A (o) B & S = A1 (o) B )
    ;
    then consider A,A1,B being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & eId V = A (o) B & S = A1 (o) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eId V = A (o) B & S = A (o) B1 )
    ;
    then consider A,B,B1 being EnvEpsTerm of V such that
    E1: [B,B1] in BetaRed(V) & eId V = A (o) B & S = A (o) B1;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eId V = eEps A & S = eEps A1 )
    ;
    then consider A,A1 being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & eId V = eEps A & S = eEps A1;
    thus thesis by E1,ENVSYN:20;
  end;
end;

theorem Th19:
  for V being non empty set, M being EnvEpsTerm of V, x being Element of V,
    S being EnvEpsTerm of V st [eLam(x,M),S] in BetaRed(V) holds
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eLam(x,M) = eLam(x0,A) & S = eLam(x0,A1) )
proof
  let V be non empty set, M be EnvEpsTerm of V, x be Element of V, S be
    EnvEpsTerm of V;
  assume [eLam(x,M),S] in BetaRed(V);
  then A1:
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        eLam(x,M) = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) ) or
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        eLam(x,M) = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) ) or
    ( ex A,B being EnvEpsTerm of V st
        eLam(x,M) = (eEps A) (@) B & S = A (o) B ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eLam(x,M) = A (@) B & S = A1 (@) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eLam(x,M) = A (@) B & S = A (@) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eLam(x,M) = eLam(x0,A) & S = eLam(x0,A1) ) or
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eLam(x,M) = eExt(A,x0,B) & S = eExt(A1,x0,B) ) or
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        eLam(x,M) = eExt(A,x0,B) & S = eExt(A,x0,B1) ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eLam(x,M) = A (o) B & S = A1 (o) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eLam(x,M) = A (o) B & S = A (o) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eLam(x,M) = eEps A & S = eEps A1 ) by Th16;
  per cases by A1;
  suppose
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        eLam(x,M) = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) )
    ;
    then consider A,B being EnvEpsTerm of V, x0 being Element of V such that
    E1: eLam(x,M) = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        eLam(x,M) = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) )
    ;
    then consider A,B,C being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: eLam(x,M) = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B being EnvEpsTerm of V st
        eLam(x,M) = (eEps A) (@) B & S = A (o) B )
    ;
    then consider A,B being EnvEpsTerm of V such that
    E1: eLam(x,M) = (eEps A) (@) B & S = A (o) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eLam(x,M) = A (@) B & S = A1 (@) B )
    ;
    then consider A,A1,B being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & eLam(x,M) = A (@) B & S = A1 (@) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eLam(x,M) = A (@) B & S = A (@) B1 )
    ;
    then consider A,B,B1 being EnvEpsTerm of V such that
    E1: [B,B1] in BetaRed(V) & eLam(x,M) = A (@) B & S = A (@) B1;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose B1:
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eLam(x,M) = eLam(x0,A) & S = eLam(x0,A1) )
    ;
    thus thesis by B1;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eLam(x,M) = eExt(A,x0,B) & S = eExt(A1,x0,B) )
    ;
    then consider A,A1,B being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [A,A1] in BetaRed(V) & eLam(x,M) = eExt(A,x0,B) & S = eExt(A1,x0,B);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        eLam(x,M) = eExt(A,x0,B) & S = eExt(A,x0,B1) )
    ;
    then consider A,B,B1 being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [B,B1] in BetaRed(V) & eLam(x,M) = eExt(A,x0,B) & S = eExt(A,x0,B1);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eLam(x,M) = A (o) B & S = A1 (o) B )
    ;
    then consider A,A1,B being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & eLam(x,M) = A (o) B & S = A1 (o) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eLam(x,M) = A (o) B & S = A (o) B1 )
    ;
    then consider A,B,B1 being EnvEpsTerm of V such that
    E1: [B,B1] in BetaRed(V) & eLam(x,M) = A (o) B & S = A (o) B1;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eLam(x,M) = eEps A & S = eEps A1 )
    ;
    then consider A,A1 being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & eLam(x,M) = eEps A & S = eEps A1;
    thus thesis by E1,ENVSYN:20;
  end;
end;

theorem Th20:
  for V being non empty set, M being EnvEpsTerm of V, S being EnvEpsTerm of
    V st [eEps M,S] in BetaRed(V) holds
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eEps M = eEps A & S = eEps A1 )
proof
  let V be non empty set, M be EnvEpsTerm of V, S be EnvEpsTerm of V;
  assume [eEps M,S] in BetaRed(V);
  then A1:
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        eEps M = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) ) or
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        eEps M = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) ) or
    ( ex A,B being EnvEpsTerm of V st
        eEps M = (eEps A) (@) B & S = A (o) B ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eEps M = A (@) B & S = A1 (@) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eEps M = A (@) B & S = A (@) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eEps M = eLam(x0,A) & S = eLam(x0,A1) ) or
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eEps M = eExt(A,x0,B) & S = eExt(A1,x0,B) ) or
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        eEps M = eExt(A,x0,B) & S = eExt(A,x0,B1) ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eEps M = A (o) B & S = A1 (o) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eEps M = A (o) B & S = A (o) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eEps M = eEps A & S = eEps A1 ) by Th16;
  per cases by A1;
  suppose
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        eEps M = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) )
    ;
    then consider A,B being EnvEpsTerm of V, x0 being Element of V such that
    E1: eEps M = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        eEps M = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) )
    ;
    then consider A,B,C being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: eEps M = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B being EnvEpsTerm of V st
        eEps M = (eEps A) (@) B & S = A (o) B )
    ;
    then consider A,B being EnvEpsTerm of V such that
    E1: eEps M = (eEps A) (@) B & S = A (o) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eEps M = A (@) B & S = A1 (@) B )
    ;
    then consider A,A1,B being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & eEps M = A (@) B & S = A1 (@) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eEps M = A (@) B & S = A (@) B1 )
    ;
    then consider A,B,B1 being EnvEpsTerm of V such that
    E1: [B,B1] in BetaRed(V) & eEps M = A (@) B & S = A (@) B1;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eEps M = eLam(x0,A) & S = eLam(x0,A1) )
    ;
    then consider A,A1 being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [A,A1] in BetaRed(V) & eEps M = eLam(x0,A) & S = eLam(x0,A1);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eEps M = eExt(A,x0,B) & S = eExt(A1,x0,B) )
    ;
    then consider A,A1,B being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [A,A1] in BetaRed(V) & eEps M = eExt(A,x0,B) & S = eExt(A1,x0,B);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        eEps M = eExt(A,x0,B) & S = eExt(A,x0,B1) )
    ;
    then consider A,B,B1 being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [B,B1] in BetaRed(V) & eEps M = eExt(A,x0,B) & S = eExt(A,x0,B1);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eEps M = A (o) B & S = A1 (o) B )
    ;
    then consider A,A1,B being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & eEps M = A (o) B & S = A1 (o) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eEps M = A (o) B & S = A (o) B1 )
    ;
    then consider A,B,B1 being EnvEpsTerm of V such that
    E1: [B,B1] in BetaRed(V) & eEps M = A (o) B & S = A (o) B1;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose B1:
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eEps M = eEps A & S = eEps A1 )
    ;
    thus thesis by B1;
  end;
end;

theorem Th21:
  for V being non empty set, M,N being EnvEpsTerm of V, S being EnvEpsTerm
    of V st [M (@) N,S] in BetaRed(V) holds
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        M (@) N = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) ) or
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        M (@) N = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) ) or
    ( ex A,B being EnvEpsTerm of V st
        M (@) N = (eEps A) (@) B & S = A (o) B ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        M (@) N = A (@) B & S = A1 (@) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        M (@) N = A (@) B & S = A (@) B1 )
proof
  let V be non empty set, M,N be EnvEpsTerm of V, S be EnvEpsTerm of V;
  assume [M (@) N,S] in BetaRed(V);
  then A1:
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        M (@) N = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) ) or
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        M (@) N = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) ) or
    ( ex A,B being EnvEpsTerm of V st
        M (@) N = (eEps A) (@) B & S = A (o) B ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        M (@) N = A (@) B & S = A1 (@) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        M (@) N = A (@) B & S = A (@) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        M (@) N = eLam(x0,A) & S = eLam(x0,A1) ) or
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        M (@) N = eExt(A,x0,B) & S = eExt(A1,x0,B) ) or
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        M (@) N = eExt(A,x0,B) & S = eExt(A,x0,B1) ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        M (@) N = A (o) B & S = A1 (o) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        M (@) N = A (o) B & S = A (o) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        M (@) N = eEps A & S = eEps A1 ) by Th16;
  per cases by A1;
  suppose B1:
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        M (@) N = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) )
    ;
    thus thesis by B1;
  end;
  suppose B1:
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        M (@) N = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) )
    ;
    thus thesis by B1;
  end;
  suppose B1:
    ( ex A,B being EnvEpsTerm of V st
        M (@) N = (eEps A) (@) B & S = A (o) B )
    ;
    thus thesis by B1;
  end;
  suppose B1:
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        M (@) N = A (@) B & S = A1 (@) B )
    ;
    thus thesis by B1;
  end;
  suppose B1:
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        M (@) N = A (@) B & S = A (@) B1 )
    ;
    thus thesis by B1;
  end;
  suppose
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        M (@) N = eLam(x0,A) & S = eLam(x0,A1) )
    ;
    then consider A,A1 being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [A,A1] in BetaRed(V) & M (@) N = eLam(x0,A) & S = eLam(x0,A1);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        M (@) N = eExt(A,x0,B) & S = eExt(A1,x0,B) )
    ;
    then consider A,A1,B being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [A,A1] in BetaRed(V) & M (@) N = eExt(A,x0,B) & S = eExt(A1,x0,B);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        M (@) N = eExt(A,x0,B) & S = eExt(A,x0,B1) )
    ;
    then consider A,B,B1 being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [B,B1] in BetaRed(V) & M (@) N = eExt(A,x0,B) & S = eExt(A,x0,B1);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        M (@) N = A (o) B & S = A1 (o) B )
    ;
    then consider A,A1,B being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & M (@) N = A (o) B & S = A1 (o) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        M (@) N = A (o) B & S = A (o) B1 )
    ;
    then consider A,B,B1 being EnvEpsTerm of V such that
    E1: [B,B1] in BetaRed(V) & M (@) N = A (o) B & S = A (o) B1;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        M (@) N = eEps A & S = eEps A1 )
    ;
    then consider A,A1 being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & M (@) N = eEps A & S = eEps A1;
    thus thesis by E1,ENVSYN:20;
  end;
end;

theorem Th22:
  for V being non empty set, M,N being EnvEpsTerm of V, S being EnvEpsTerm
    of V st [M (o) N,S] in BetaRed(V) holds
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        M (o) N = A (o) B & S = A1 (o) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        M (o) N = A (o) B & S = A (o) B1 )
proof
  let V be non empty set, M,N be EnvEpsTerm of V, S be EnvEpsTerm of V;
  assume [M (o) N,S] in BetaRed(V);
  then A1:
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        M (o) N = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) ) or
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        M (o) N = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) ) or
    ( ex A,B being EnvEpsTerm of V st
        M (o) N = (eEps A) (@) B & S = A (o) B ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        M (o) N = A (@) B & S = A1 (@) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        M (o) N = A (@) B & S = A (@) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        M (o) N = eLam(x0,A) & S = eLam(x0,A1) ) or
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        M (o) N = eExt(A,x0,B) & S = eExt(A1,x0,B) ) or
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        M (o) N = eExt(A,x0,B) & S = eExt(A,x0,B1) ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        M (o) N = A (o) B & S = A1 (o) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        M (o) N = A (o) B & S = A (o) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        M (o) N = eEps A & S = eEps A1 ) by Th16;
  per cases by A1;
  suppose
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        M (o) N = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) )
    ;
    then consider A,B being EnvEpsTerm of V, x0 being Element of V such that
    E1: M (o) N = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        M (o) N = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) )
    ;
    then consider A,B,C being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: M (o) N = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B being EnvEpsTerm of V st
        M (o) N = (eEps A) (@) B & S = A (o) B )
    ;
    then consider A,B being EnvEpsTerm of V such that
    E1: M (o) N = (eEps A) (@) B & S = A (o) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        M (o) N = A (@) B & S = A1 (@) B )
    ;
    then consider A,A1,B being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & M (o) N = A (@) B & S = A1 (@) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        M (o) N = A (@) B & S = A (@) B1 )
    ;
    then consider A,B,B1 being EnvEpsTerm of V such that
    E1: [B,B1] in BetaRed(V) & M (o) N = A (@) B & S = A (@) B1;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        M (o) N = eLam(x0,A) & S = eLam(x0,A1) )
    ;
    then consider A,A1 being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [A,A1] in BetaRed(V) & M (o) N = eLam(x0,A) & S = eLam(x0,A1);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        M (o) N = eExt(A,x0,B) & S = eExt(A1,x0,B) )
    ;
    then consider A,A1,B being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [A,A1] in BetaRed(V) & M (o) N = eExt(A,x0,B) & S = eExt(A1,x0,B);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        M (o) N = eExt(A,x0,B) & S = eExt(A,x0,B1) )
    ;
    then consider A,B,B1 being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [B,B1] in BetaRed(V) & M (o) N = eExt(A,x0,B) & S = eExt(A,x0,B1);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose B1:
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        M (o) N = A (o) B & S = A1 (o) B )
    ;
    thus thesis by B1;
  end;
  suppose B1:
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        M (o) N = A (o) B & S = A (o) B1 )
    ;
    thus thesis by B1;
  end;
  suppose
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        M (o) N = eEps A & S = eEps A1 )
    ;
    then consider A,A1 being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & M (o) N = eEps A & S = eEps A1;
    thus thesis by E1,ENVSYN:20;
  end;
end;

theorem Th23:
  for V being non empty set, M,N being EnvEpsTerm of V, x being Element of
    V, S being EnvEpsTerm of V st [eExt(M,x,N),S] in BetaRed(V) holds
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eExt(M,x,N) = eExt(A,x0,B) & S = eExt(A1,x0,B) ) or
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        eExt(M,x,N) = eExt(A,x0,B) & S = eExt(A,x0,B1) )
proof
  let V be non empty set, M,N be EnvEpsTerm of V, x be Element of V, S be
    EnvEpsTerm of V;
  assume [eExt(M,x,N),S] in BetaRed(V);
  then A1:
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        eExt(M,x,N) = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) ) or
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        eExt(M,x,N) = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) ) or
    ( ex A,B being EnvEpsTerm of V st
        eExt(M,x,N) = (eEps A) (@) B & S = A (o) B ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eExt(M,x,N) = A (@) B & S = A1 (@) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eExt(M,x,N) = A (@) B & S = A (@) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eExt(M,x,N) = eLam(x0,A) & S = eLam(x0,A1) ) or
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eExt(M,x,N) = eExt(A,x0,B) & S = eExt(A1,x0,B) ) or
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        eExt(M,x,N) = eExt(A,x0,B) & S = eExt(A,x0,B1) ) or
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eExt(M,x,N) = A (o) B & S = A1 (o) B ) or
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eExt(M,x,N) = A (o) B & S = A (o) B1 ) or
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eExt(M,x,N) = eEps A & S = eEps A1 ) by Th16;
  per cases by A1;
  suppose
    ( ex A,B being EnvEpsTerm of V, x0 being Element of V st
        eExt(M,x,N) = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V) )
    ;
    then consider A,B being EnvEpsTerm of V, x0 being Element of V such that
    E1: eExt(M,x,N) = eLam(x0,A) (@) B & S = A (o) eExt(B,x0,eId V);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,C being EnvEpsTerm of V, x0 being Element of V st
        eExt(M,x,N) = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C) )
    ;
    then consider A,B,C being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: eExt(M,x,N) = (eLam(x0,A) (o) C) (@) B & S = A (o) eExt(B,x0,C);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B being EnvEpsTerm of V st
        eExt(M,x,N) = (eEps A) (@) B & S = A (o) B )
    ;
    then consider A,B being EnvEpsTerm of V such that
    E1: eExt(M,x,N) = (eEps A) (@) B & S = A (o) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eExt(M,x,N) = A (@) B & S = A1 (@) B )
    ;
    then consider A,A1,B being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & eExt(M,x,N) = A (@) B & S = A1 (@) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eExt(M,x,N) = A (@) B & S = A (@) B1 )
    ;
    then consider A,B,B1 being EnvEpsTerm of V such that
    E1: [B,B1] in BetaRed(V) & eExt(M,x,N) = A (@) B & S = A (@) B1;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1 being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eExt(M,x,N) = eLam(x0,A) & S = eLam(x0,A1) )
    ;
    then consider A,A1 being EnvEpsTerm of V, x0 being Element of V such
      that
    E1: [A,A1] in BetaRed(V) & eExt(M,x,N) = eLam(x0,A) & S = eLam(x0,A1);
    thus thesis by E1,ENVSYN:20;
  end;
  suppose B1:
    ( ex A,A1,B being EnvEpsTerm of V, x0 being Element of V st [A,A1] in
    BetaRed(V) &
        eExt(M,x,N) = eExt(A,x0,B) & S = eExt(A1,x0,B) )
    ;
    thus thesis by B1;
  end;
  suppose B1:
    ( ex A,B,B1 being EnvEpsTerm of V, x0 being Element of V st [B,B1] in
    BetaRed(V) &
        eExt(M,x,N) = eExt(A,x0,B) & S = eExt(A,x0,B1) )
    ;
    thus thesis by B1;
  end;
  suppose
    ( ex A,A1,B being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eExt(M,x,N) = A (o) B & S = A1 (o) B )
    ;
    then consider A,A1,B being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & eExt(M,x,N) = A (o) B & S = A1 (o) B;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,B,B1 being EnvEpsTerm of V st [B,B1] in BetaRed(V) &
        eExt(M,x,N) = A (o) B & S = A (o) B1 )
    ;
    then consider A,B,B1 being EnvEpsTerm of V such that
    E1: [B,B1] in BetaRed(V) & eExt(M,x,N) = A (o) B & S = A (o) B1;
    thus thesis by E1,ENVSYN:20;
  end;
  suppose
    ( ex A,A1 being EnvEpsTerm of V st [A,A1] in BetaRed(V) &
        eExt(M,x,N) = eEps A & S = eEps A1 )
    ;
    then consider A,A1 being EnvEpsTerm of V such that
    E1: [A,A1] in BetaRed(V) & eExt(M,x,N) = eEps A & S = eEps A1;
    thus thesis by E1,ENVSYN:20;
  end;
end;

begin :: Multi-step congruence for the beta reduction

theorem Th24:
  for V being non empty set, M,M1,N being EnvEpsTerm of V st BetaRed(V)
    reduces M,M1 holds
  BetaRed(V) reduces M (@) N, M1 (@) N
proof
  let V be non empty set, M,M1,N be EnvEpsTerm of V;
  assume BetaRed(V) reduces M,M1;
  then CC BetaRoot(V) reduces M,M1 by Def2;
  then CC BetaRoot(V) reduces M (@) N, M1 (@) N by ENVCC:23;
  hence thesis by Def2;
end;

theorem Th25:
  for V being non empty set, M,N,N1 being EnvEpsTerm of V st BetaRed(V)
    reduces N,N1 holds
  BetaRed(V) reduces M (@) N, M (@) N1
proof
  let V be non empty set, M,N,N1 be EnvEpsTerm of V;
  assume BetaRed(V) reduces N,N1;
  then CC BetaRoot(V) reduces N,N1 by Def2;
  then CC BetaRoot(V) reduces M (@) N, M (@) N1 by ENVCC:24;
  hence thesis by Def2;
end;

theorem Th26:
  for V being non empty set, M,M1 being EnvEpsTerm of V, x being Element of
    V st BetaRed(V) reduces M,M1 holds
  BetaRed(V) reduces eLam(x,M), eLam(x,M1)
proof
  let V be non empty set, M,M1 be EnvEpsTerm of V, x be Element of V;
  assume BetaRed(V) reduces M,M1;
  then CC BetaRoot(V) reduces M,M1 by Def2;
  then CC BetaRoot(V) reduces eLam(x,M), eLam(x,M1) by ENVCC:25;
  hence thesis by Def2;
end;

theorem Th27:
  for V being non empty set, M,M1,N being EnvEpsTerm of V, x being Element
    of V st BetaRed(V) reduces M,M1 holds
  BetaRed(V) reduces eExt(M,x,N), eExt(M1,x,N)
proof
  let V be non empty set, M,M1,N be EnvEpsTerm of V, x be Element of V;
  assume BetaRed(V) reduces M,M1;
  then CC BetaRoot(V) reduces M,M1 by Def2;
  then CC BetaRoot(V) reduces eExt(M,x,N), eExt(M1,x,N) by ENVCC:26;
  hence thesis by Def2;
end;

theorem Th28:
  for V being non empty set, M,N,N1 being EnvEpsTerm of V, x being Element
    of V st BetaRed(V) reduces N,N1 holds
  BetaRed(V) reduces eExt(M,x,N), eExt(M,x,N1)
proof
  let V be non empty set, M,N,N1 be EnvEpsTerm of V, x be Element of V;
  assume BetaRed(V) reduces N,N1;
  then CC BetaRoot(V) reduces N,N1 by Def2;
  then CC BetaRoot(V) reduces eExt(M,x,N), eExt(M,x,N1) by ENVCC:27;
  hence thesis by Def2;
end;

theorem Th29:
  for V being non empty set, M,M1,N being EnvEpsTerm of V st BetaRed(V)
    reduces M,M1 holds
  BetaRed(V) reduces M (o) N, M1 (o) N
proof
  let V be non empty set, M,M1,N be EnvEpsTerm of V;
  assume BetaRed(V) reduces M,M1;
  then CC BetaRoot(V) reduces M,M1 by Def2;
  then CC BetaRoot(V) reduces M (o) N, M1 (o) N by ENVCC:28;
  hence thesis by Def2;
end;

theorem Th30:
  for V being non empty set, M,N,N1 being EnvEpsTerm of V st BetaRed(V)
    reduces N,N1 holds
  BetaRed(V) reduces M (o) N, M (o) N1
proof
  let V be non empty set, M,N,N1 be EnvEpsTerm of V;
  assume BetaRed(V) reduces N,N1;
  then CC BetaRoot(V) reduces N,N1 by Def2;
  then CC BetaRoot(V) reduces M (o) N, M (o) N1 by ENVCC:29;
  hence thesis by Def2;
end;

theorem Th31:
  for V being non empty set, M,M1 being EnvEpsTerm of V st BetaRed(V)
    reduces M,M1 holds
  BetaRed(V) reduces eEps M, eEps M1
proof
  let V be non empty set, M,M1 be EnvEpsTerm of V;
  assume BetaRed(V) reduces M,M1;
  then CC BetaRoot(V) reduces M,M1 by Def2;
  then CC BetaRoot(V) reduces eEps M, eEps M1 by ENVCC:30;
  hence thesis by Def2;
end;

begin :: The beta/sigma reduction

definition
  let V be non empty set;
  func BetaSigmaRoot(V) -> EnvEpsRel of V equals
  :Def3:
  BetaRoot(V) \/ SigmaRoot(V);
  coherence
  proof
    set G = EnvEpsGram(V);
    BetaRoot(V) c= [:TS G, TS G:] & SigmaRoot(V) c= [:TS G, TS G:];
    hence thesis by XBOOLE_1:8;
  end;
end;

definition
  let V be non empty set;
  func BetaSigmaRed(V) -> EnvEpsRel of V equals
  :Def4:
  CC BetaSigmaRoot(V);
  coherence;
end;

theorem Th32:
  for V being non empty set holds
  BetaSigmaRed(V) = BetaRed(V) \/ SigmaRed(V)
proof
  let V be non empty set;
  thus BetaSigmaRed(V) = CC BetaSigmaRoot(V) by Def4
    .= CC (BetaRoot(V) \/ SigmaRoot(V)) by Def3
    .= CC BetaRoot(V) \/ CC SigmaRoot(V) by ENVCC:15
    .= BetaRed(V) \/ CC SigmaRoot(V) by Def2
    .= BetaRed(V) \/ SigmaRed(V) by ENVSIG:def 2;
end;

theorem Th33:
  for V being non empty set, M,N being EnvEpsTerm of V holds
  ( [M,N] in BetaSigmaRed(V) iff
    [M,N] in BetaRed(V) or [M,N] in SigmaRed(V) )
proof
  let V be non empty set, M,N be EnvEpsTerm of V;
  BetaSigmaRed(V) = BetaRed(V) \/ SigmaRed(V) by Th32;
  hence thesis by XBOOLE_0:def 3;
end;

theorem Th34:
  for V being non empty set holds
  BetaRoot(V) c= BetaSigmaRoot(V) & SigmaRoot(V) c= BetaSigmaRoot(V)
proof
  let V be non empty set;
  BetaSigmaRoot(V) = BetaRoot(V) \/ SigmaRoot(V) by Def3;
  hence thesis by XBOOLE_1:7;
end;

begin :: The nineteen rules of the beta/sigma reduction

:: beta
theorem Th35:
  for V being non empty set, M,N being EnvEpsTerm of V, x being Element of V
    holds
  [eLam(x,M) (@) N, M (o) eExt(N,x,eId V)] in BetaSigmaRed(V)
proof
  let V be non empty set, M,N be EnvEpsTerm of V, x be Element of V;
  A1: [eLam(x,M) (@) N, M (o) eExt(N,x,eId V)] in BetaRoot(V) by Th2;
  BetaRoot(V) c= BetaSigmaRoot(V) by Th34;
  then A2: [eLam(x,M) (@) N, M (o) eExt(N,x,eId V)] in BetaSigmaRoot(V) by
    A1;
  BetaSigmaRoot(V) c= CC BetaSigmaRoot(V) by ENVCC:4;
  hence thesis by A2,Def4;
end;

:: betaClos
theorem Th36:
  for V being non empty set, M,N,L being EnvEpsTerm of V, x being Element of
    V holds
  [(eLam(x,M) (o) L) (@) N, M (o) eExt(N,x,L)] in BetaSigmaRed(V)
proof
  let V be non empty set, M,N,L be EnvEpsTerm of V, x be Element of V;
  A1: [(eLam(x,M) (o) L) (@) N, M (o) eExt(N,x,L)] in BetaRoot(V) by Th3;
  BetaRoot(V) c= BetaSigmaRoot(V) by Th34;
  then A2: [(eLam(x,M) (o) L) (@) N, M (o) eExt(N,x,L)] in BetaSigmaRoot(V)
    by A1;
  BetaSigmaRoot(V) c= CC BetaSigmaRoot(V) by ENVCC:4;
  hence thesis by A2,Def4;
end;

:: compEps
theorem Th37:
  for V being non empty set, M,N being EnvEpsTerm of V holds
  [(eEps M) (@) N, M (o) N] in BetaSigmaRed(V)
proof
  let V be non empty set, M,N be EnvEpsTerm of V;
  A1: [(eEps M) (@) N, M (o) N] in BetaRoot(V) by Th4;
  BetaRoot(V) c= BetaSigmaRoot(V) by Th34;
  then A2: [(eEps M) (@) N, M (o) N] in BetaSigmaRoot(V) by A1;
  BetaSigmaRoot(V) c= CC BetaSigmaRoot(V) by ENVCC:4;
  hence thesis by A2,Def4;
end;

:: assoc
theorem Th38:
  for V being non empty set, M,N,L being EnvEpsTerm of V holds
  [(M (o) N) (o) L, M (o) (N (o) L)] in BetaSigmaRed(V)
proof
  let V be non empty set, M,N,L be EnvEpsTerm of V;
  A1: [(M (o) N) (o) L, M (o) (N (o) L)] in SigmaRoot(V) by ENVSIG:2;
  SigmaRoot(V) c= BetaSigmaRoot(V) by Th34;
  then A2: [(M (o) N) (o) L, M (o) (N (o) L)] in BetaSigmaRoot(V) by A1;
  BetaSigmaRoot(V) c= CC BetaSigmaRoot(V) by ENVCC:4;
  hence thesis by A2,Def4;
end;

:: idL
theorem Th39:
  for V being non empty set, M being EnvEpsTerm of V holds
  [(eId V) (o) M, M] in BetaSigmaRed(V)
proof
  let V be non empty set, M be EnvEpsTerm of V;
  A1: [(eId V) (o) M, M] in SigmaRoot(V) by ENVSIG:3;
  SigmaRoot(V) c= BetaSigmaRoot(V) by Th34;
  then A2: [(eId V) (o) M, M] in BetaSigmaRoot(V) by A1;
  BetaSigmaRoot(V) c= CC BetaSigmaRoot(V) by ENVCC:4;
  hence thesis by A2,Def4;
end;

:: idR
theorem Th40:
  for V being non empty set, M being EnvEpsTerm of V holds
  [M (o) (eId V), M] in BetaSigmaRed(V)
proof
  let V be non empty set, M be EnvEpsTerm of V;
  A1: [M (o) (eId V), M] in SigmaRoot(V) by ENVSIG:4;
  SigmaRoot(V) c= BetaSigmaRoot(V) by Th34;
  then A2: [M (o) (eId V), M] in BetaSigmaRoot(V) by A1;
  BetaSigmaRoot(V) c= CC BetaSigmaRoot(V) by ENVCC:4;
  hence thesis by A2,Def4;
end;

:: dExt
theorem Th41:
  for V being non empty set, L,M,N being EnvEpsTerm of V, x being Element of
    V holds
  [eExt(L,x,M) (o) N, eExt(L (o) N, x, M (o) N)] in BetaSigmaRed(V)
proof
  let V be non empty set, L,M,N be EnvEpsTerm of V, x be Element of V;
  A1: [eExt(L,x,M) (o) N, eExt(L (o) N, x, M (o) N)] in SigmaRoot(V) by
    ENVSIG:5;
  SigmaRoot(V) c= BetaSigmaRoot(V) by Th34;
  then A2: [eExt(L,x,M) (o) N, eExt(L (o) N, x, M (o) N)] in
    BetaSigmaRoot(V) by A1;
  BetaSigmaRoot(V) c= CC BetaSigmaRoot(V) by ENVCC:4;
  hence thesis by A2,Def4;
end;

:: varRef
theorem Th42:
  for V being non empty set, M,N being EnvEpsTerm of V, x being Element of V
    holds
  [(eVar x) (o) eExt(M,x,N), M] in BetaSigmaRed(V)
proof
  let V be non empty set, M,N be EnvEpsTerm of V, x be Element of V;
  A1: [(eVar x) (o) eExt(M,x,N), M] in SigmaRoot(V) by ENVSIG:6;
  SigmaRoot(V) c= BetaSigmaRoot(V) by Th34;
  then A2: [(eVar x) (o) eExt(M,x,N), M] in BetaSigmaRoot(V) by A1;
  BetaSigmaRoot(V) c= CC BetaSigmaRoot(V) by ENVCC:4;
  hence thesis by A2,Def4;
end;

:: varSkip
theorem Th43:
  for V being non empty set, M,N being EnvEpsTerm of V, x,y being Element of
    V st x <> y holds
  [(eVar x) (o) eExt(M,y,N), (eVar x) (o) N] in BetaSigmaRed(V)
proof
  let V be non empty set, M,N be EnvEpsTerm of V, x,y be Element of V;
  assume A0: x <> y;
  A1: [(eVar x) (o) eExt(M,y,N), (eVar x) (o) N] in SigmaRoot(V) by
    A0,ENVSIG:7;
  SigmaRoot(V) c= BetaSigmaRoot(V) by Th34;
  then A2: [(eVar x) (o) eExt(M,y,N), (eVar x) (o) N] in BetaSigmaRoot(V) by
    A1;
  BetaSigmaRoot(V) c= CC BetaSigmaRoot(V) by ENVCC:4;
  hence thesis by A2,Def4;
end;

:: dApp
theorem Th44:
  for V being non empty set, M,N,L being EnvEpsTerm of V holds
  [(M (@) N) (o) L, (M (o) L) (@) (N (o) L)] in BetaSigmaRed(V)
proof
  let V be non empty set, M,N,L be EnvEpsTerm of V;
  A1: [(M (@) N) (o) L, (M (o) L) (@) (N (o) L)] in SigmaRoot(V) by
    ENVSIG:8;
  SigmaRoot(V) c= BetaSigmaRoot(V) by Th34;
  then A2: [(M (@) N) (o) L, (M (o) L) (@) (N (o) L)] in BetaSigmaRoot(V) by
    A1;
  BetaSigmaRoot(V) c= CC BetaSigmaRoot(V) by ENVCC:4;
  hence thesis by A2,Def4;
end;

:: epsEps
theorem Th45:
  for V being non empty set, M,N being EnvEpsTerm of V holds
  [(eEps M) (o) N, eEps M] in BetaSigmaRed(V)
proof
  let V be non empty set, M,N be EnvEpsTerm of V;
  A1: [(eEps M) (o) N, eEps M] in SigmaRoot(V) by ENVSIG:9;
  SigmaRoot(V) c= BetaSigmaRoot(V) by Th34;
  then A2: [(eEps M) (o) N, eEps M] in BetaSigmaRoot(V) by A1;
  BetaSigmaRoot(V) c= CC BetaSigmaRoot(V) by ENVCC:4;
  hence thesis by A2,Def4;
end;

theorem Th46:
  for V being non empty set, M,M1,N being EnvEpsTerm of V st [M,M1] in
    BetaSigmaRed(V) holds
  [M (@) N, M1 (@) N] in BetaSigmaRed(V)
proof
  let V be non empty set, M,M1,N be EnvEpsTerm of V;
  assume [M,M1] in BetaSigmaRed(V);
  then [M,M1] in CC BetaSigmaRoot(V) by Def4;
  then [M (@) N, M1 (@) N] in CC BetaSigmaRoot(V) by ENVCC:5;
  hence thesis by Def4;
end;

theorem Th47:
  for V being non empty set, M,N,N1 being EnvEpsTerm of V st [N,N1] in
    BetaSigmaRed(V) holds
  [M (@) N, M (@) N1] in BetaSigmaRed(V)
proof
  let V be non empty set, M,N,N1 be EnvEpsTerm of V;
  assume [N,N1] in BetaSigmaRed(V);
  then [N,N1] in CC BetaSigmaRoot(V) by Def4;
  then [M (@) N, M (@) N1] in CC BetaSigmaRoot(V) by ENVCC:6;
  hence thesis by Def4;
end;

theorem Th48:
  for V being non empty set, M,M1 being EnvEpsTerm of V, x being Element of
    V st [M,M1] in BetaSigmaRed(V) holds
  [eLam(x,M), eLam(x,M1)] in BetaSigmaRed(V)
proof
  let V be non empty set, M,M1 be EnvEpsTerm of V, x be Element of V;
  assume [M,M1] in BetaSigmaRed(V);
  then [M,M1] in CC BetaSigmaRoot(V) by Def4;
  then [eLam(x,M), eLam(x,M1)] in CC BetaSigmaRoot(V) by ENVCC:7;
  hence thesis by Def4;
end;

theorem Th49:
  for V being non empty set, M,M1,N being EnvEpsTerm of V, x being Element
    of V st [M,M1] in BetaSigmaRed(V) holds
  [eExt(M,x,N), eExt(M1,x,N)] in BetaSigmaRed(V)
proof
  let V be non empty set, M,M1,N be EnvEpsTerm of V, x be Element of V;
  assume [M,M1] in BetaSigmaRed(V);
  then [M,M1] in CC BetaSigmaRoot(V) by Def4;
  then [eExt(M,x,N), eExt(M1,x,N)] in CC BetaSigmaRoot(V) by ENVCC:8;
  hence thesis by Def4;
end;

theorem Th50:
  for V being non empty set, M,N,N1 being EnvEpsTerm of V, x being Element
    of V st [N,N1] in BetaSigmaRed(V) holds
  [eExt(M,x,N), eExt(M,x,N1)] in BetaSigmaRed(V)
proof
  let V be non empty set, M,N,N1 be EnvEpsTerm of V, x be Element of V;
  assume [N,N1] in BetaSigmaRed(V);
  then [N,N1] in CC BetaSigmaRoot(V) by Def4;
  then [eExt(M,x,N), eExt(M,x,N1)] in CC BetaSigmaRoot(V) by ENVCC:9;
  hence thesis by Def4;
end;

theorem Th51:
  for V being non empty set, M,M1,N being EnvEpsTerm of V st [M,M1] in
    BetaSigmaRed(V) holds
  [M (o) N, M1 (o) N] in BetaSigmaRed(V)
proof
  let V be non empty set, M,M1,N be EnvEpsTerm of V;
  assume [M,M1] in BetaSigmaRed(V);
  then [M,M1] in CC BetaSigmaRoot(V) by Def4;
  then [M (o) N, M1 (o) N] in CC BetaSigmaRoot(V) by ENVCC:10;
  hence thesis by Def4;
end;

theorem Th52:
  for V being non empty set, M,N,N1 being EnvEpsTerm of V st [N,N1] in
    BetaSigmaRed(V) holds
  [M (o) N, M (o) N1] in BetaSigmaRed(V)
proof
  let V be non empty set, M,N,N1 be EnvEpsTerm of V;
  assume [N,N1] in BetaSigmaRed(V);
  then [N,N1] in CC BetaSigmaRoot(V) by Def4;
  then [M (o) N, M (o) N1] in CC BetaSigmaRoot(V) by ENVCC:11;
  hence thesis by Def4;
end;

theorem Th53:
  for V being non empty set, M,M1 being EnvEpsTerm of V st [M,M1] in
    BetaSigmaRed(V) holds
  [eEps M, eEps M1] in BetaSigmaRed(V)
proof
  let V be non empty set, M,M1 be EnvEpsTerm of V;
  assume [M,M1] in BetaSigmaRed(V);
  then [M,M1] in CC BetaSigmaRoot(V) by Def4;
  then [eEps M, eEps M1] in CC BetaSigmaRoot(V) by ENVCC:12;
  hence thesis by Def4;
end;

begin :: Multi-step congruence for the beta/sigma reduction

theorem Th54:
  for V being non empty set, M,M1,N being EnvEpsTerm of V st BetaSigmaRed(V)
    reduces M,M1 holds
  BetaSigmaRed(V) reduces M (@) N, M1 (@) N
proof
  let V be non empty set, M,M1,N be EnvEpsTerm of V;
  assume BetaSigmaRed(V) reduces M,M1;
  then CC BetaSigmaRoot(V) reduces M,M1 by Def4;
  then CC BetaSigmaRoot(V) reduces M (@) N, M1 (@) N by ENVCC:23;
  hence thesis by Def4;
end;

theorem Th55:
  for V being non empty set, M,N,N1 being EnvEpsTerm of V st BetaSigmaRed(V)
    reduces N,N1 holds
  BetaSigmaRed(V) reduces M (@) N, M (@) N1
proof
  let V be non empty set, M,N,N1 be EnvEpsTerm of V;
  assume BetaSigmaRed(V) reduces N,N1;
  then CC BetaSigmaRoot(V) reduces N,N1 by Def4;
  then CC BetaSigmaRoot(V) reduces M (@) N, M (@) N1 by ENVCC:24;
  hence thesis by Def4;
end;

theorem Th56:
  for V being non empty set, M,M1 being EnvEpsTerm of V, x being Element of
    V st BetaSigmaRed(V) reduces M,M1 holds
  BetaSigmaRed(V) reduces eLam(x,M), eLam(x,M1)
proof
  let V be non empty set, M,M1 be EnvEpsTerm of V, x be Element of V;
  assume BetaSigmaRed(V) reduces M,M1;
  then CC BetaSigmaRoot(V) reduces M,M1 by Def4;
  then CC BetaSigmaRoot(V) reduces eLam(x,M), eLam(x,M1) by ENVCC:25;
  hence thesis by Def4;
end;

theorem Th57:
  for V being non empty set, M,M1,N being EnvEpsTerm of V, x being Element
    of V st BetaSigmaRed(V) reduces M,M1 holds
  BetaSigmaRed(V) reduces eExt(M,x,N), eExt(M1,x,N)
proof
  let V be non empty set, M,M1,N be EnvEpsTerm of V, x be Element of V;
  assume BetaSigmaRed(V) reduces M,M1;
  then CC BetaSigmaRoot(V) reduces M,M1 by Def4;
  then CC BetaSigmaRoot(V) reduces eExt(M,x,N), eExt(M1,x,N) by ENVCC:26;
  hence thesis by Def4;
end;

theorem Th58:
  for V being non empty set, M,N,N1 being EnvEpsTerm of V, x being Element
    of V st BetaSigmaRed(V) reduces N,N1 holds
  BetaSigmaRed(V) reduces eExt(M,x,N), eExt(M,x,N1)
proof
  let V be non empty set, M,N,N1 be EnvEpsTerm of V, x be Element of V;
  assume BetaSigmaRed(V) reduces N,N1;
  then CC BetaSigmaRoot(V) reduces N,N1 by Def4;
  then CC BetaSigmaRoot(V) reduces eExt(M,x,N), eExt(M,x,N1) by ENVCC:27;
  hence thesis by Def4;
end;

theorem Th59:
  for V being non empty set, M,M1,N being EnvEpsTerm of V st BetaSigmaRed(V)
    reduces M,M1 holds
  BetaSigmaRed(V) reduces M (o) N, M1 (o) N
proof
  let V be non empty set, M,M1,N be EnvEpsTerm of V;
  assume BetaSigmaRed(V) reduces M,M1;
  then CC BetaSigmaRoot(V) reduces M,M1 by Def4;
  then CC BetaSigmaRoot(V) reduces M (o) N, M1 (o) N by ENVCC:28;
  hence thesis by Def4;
end;

theorem Th60:
  for V being non empty set, M,N,N1 being EnvEpsTerm of V st BetaSigmaRed(V)
    reduces N,N1 holds
  BetaSigmaRed(V) reduces M (o) N, M (o) N1
proof
  let V be non empty set, M,N,N1 be EnvEpsTerm of V;
  assume BetaSigmaRed(V) reduces N,N1;
  then CC BetaSigmaRoot(V) reduces N,N1 by Def4;
  then CC BetaSigmaRoot(V) reduces M (o) N, M (o) N1 by ENVCC:29;
  hence thesis by Def4;
end;

theorem Th61:
  for V being non empty set, M,M1 being EnvEpsTerm of V st BetaSigmaRed(V)
    reduces M,M1 holds
  BetaSigmaRed(V) reduces eEps M, eEps M1
proof
  let V be non empty set, M,M1 be EnvEpsTerm of V;
  assume BetaSigmaRed(V) reduces M,M1;
  then CC BetaSigmaRoot(V) reduces M,M1 by Def4;
  then CC BetaSigmaRoot(V) reduces eEps M, eEps M1 by ENVCC:30;
  hence thesis by Def4;
end;
