:: Lifting beta-sigma steps along the translation, and confluence

environ

 vocabularies NUMBERS, XBOOLE_0, SUBSET_1, TARSKI, ZFMISC_1, FINSEQ_1,
      RELAT_1, FUNCT_1, ORDINAL1, CARD_1, ARYTM_3, XXREAL_0, NAT_1, TREES_1,
      TREES_2, TREES_3, TREES_4, LANG1, STRUCT_0, DTCONSTR, MCART_1, XTUPLE_0,
      FINSET_1, TDGROUP, FUNCOP_1, ARYTM_1, FUNCT_7, XREAL_0, XCMPLX_0,
      REWRITE1, PBOOLE, ENVSYN, ENVLEN, ENVBETA, FRENV_1, FRENV_2, FRENV_3,
      ENVCC, ENVSIG;
 notations TARSKI, XBOOLE_0, ZFMISC_1, SUBSET_1, ORDINAL1, NUMBERS, XCMPLX_0,
      XXREAL_0, NAT_1, RELAT_1, RELSET_1, FUNCT_1, FUNCT_2, FINSEQ_1,
      FINSEQ_2, MCART_1, XTUPLE_0, DOMAIN_1, STRUCT_0, LANG1, TREES_1,
      TREES_2, TREES_3, TREES_4, DTCONSTR, FUNCOP_1, XREAL_0, PBOOLE,
      REWRITE1, ENVSYN, ENVLEN, ENVBETA, FRENV_1, FRENV_2, FRENV_3, ENVCC,
      ENVSIG;
 constructors NUMBERS, XCMPLX_0, XXREAL_0, NAT_1, RELSET_1, FUNCT_2, FINSEQ_1,
      FINSEQ_2, MCART_1, XTUPLE_0, DOMAIN_1, STRUCT_0, LANG1, TREES_1,
      TREES_2, TREES_3, TREES_4, DTCONSTR, PARTFUN1, BINOP_1, SETWISEO,
      XREAL_0, FUNCOP_1, SUBSET_1, CARD_3, FINSEQOP, FINSEQ_4, FINSOP_1,
      PRE_POLY, FUNCT_1, RELAT_1, PBOOLE, REWRITE1, ENVSYN, ENVLEN, ENVBETA,
      FRENV_1, FRENV_2, FRENV_3, ENVCC, ENVSIG;
 registrations XBOOLE_0, SUBSET_1, RELAT_1, FUNCT_1, ORDINAL1, XREAL_0, NAT_1,
      FINSEQ_1, FINSEQ_2, FINSET_1, CARD_1, STRUCT_0, LANG1, TREES_1, TREES_2,
      TREES_3, TREES_4, DTCONSTR, XTUPLE_0, VALUED_0, FUNCOP_1, XCMPLX_0,
      XXREAL_0, NUMBERS, MEMBERED, PBOOLE, REWRITE1, ENVSYN, ENVPEAK,
      FRENV_1, FRENV_3, ENVSIG;
 requirements NUMERALS, REAL, BOOLE, SUBSET, ARITHM;
 definitions TARSKI, XBOOLE_0, DTCONSTR, TREES_3, TREES_4, RELAT_1, FUNCT_1,
      FINSEQ_1, FUNCOP_1, SUBSET_1, REWRITE1, ENVSYN, ENVLEN, FRENV_2;
 theorems TARSKI, XBOOLE_0, ZFMISC_1, XTUPLE_0, RELAT_1, REWRITE1, ENVSYN,
      ENVLEN, ENVSIG, ENVBETA, ENVCONF, FRENV_1, FRENV_2, FRENV_3, FRENV_4;
 schemes ENVKEY;
begin :: Inverting an environment abstraction

reserve V for non empty set;

theorem Th1:
  for A,Q being EnvEpsTerm of V st [eEps A, Q] in BetaSigmaRed(V)
  ex A1 being EnvEpsTerm of V st Q = eEps A1 & [A,A1] in BetaSigmaRed(V)
proof
  let A,Q be EnvEpsTerm of V;
  assume A1: [eEps A, Q] in BetaSigmaRed(V);
  per cases by A1,ENVBETA:33;
  suppose [eEps A, Q] in BetaRed(V);
    then consider M2,M3 being EnvEpsTerm of V such that
    B1: [M2,M3] in BetaRed(V) & eEps A = eEps M2 & Q = eEps M3
      by ENVBETA:20;
    B2: A = M2 by B1,ENVSYN:12;
    [M2,M3] in BetaSigmaRed(V) by B1,ENVBETA:33;
    hence thesis by B1,B2;
  end;
  suppose [eEps A, Q] in SigmaRed(V);
    then consider M2,M3 being EnvEpsTerm of V such that
    B1: [M2,M3] in SigmaRed(V) & eEps A = eEps M2 & Q = eEps M3
      by ENVSIG:30;
    B2: A = M2 by B1,ENVSYN:12;
    [M2,M3] in BetaSigmaRed(V) by B1,ENVBETA:33;
    hence thesis by B1,B2;
  end;
end;

theorem Th2:
  for A,Q being EnvEpsTerm of V st BetaSigmaRed(V) reduces eEps A, Q
  ex A1 being EnvEpsTerm of V st Q = eEps A1 &
    BetaSigmaRed(V) reduces A, A1
proof
  let A,Q be EnvEpsTerm of V;
  set G = EnvEpsGram(V);
  defpred P[object] means ex A1 being EnvEpsTerm of V st $1 = eEps A1 &
    BetaSigmaRed(V) reduces A, A1;
  B1: for a,b being object st P[a] & [a,b] in BetaSigmaRed(V) holds P[b]
  proof
    let a,b be object;
    assume that C1: P[a] and C2: [a,b] in BetaSigmaRed(V);
    consider A1 being EnvEpsTerm of V such that
    C3: a = eEps A1 & BetaSigmaRed(V) reduces A, A1 by C1;
    BetaSigmaRed(V) c= [:TS G, TS G:];
    then [a,b] in [:TS G, TS G:] by C2;
    then b in TS G by ZFMISC_1:87;
    then reconsider b1 = b as EnvEpsTerm of V;
    [eEps A1, b1] in BetaSigmaRed(V) by C2,C3;
    then consider A2 being EnvEpsTerm of V such that
    C4: b1 = eEps A2 & [A1,A2] in BetaSigmaRed(V) by Th1;
    BetaSigmaRed(V) reduces A1,A2 by C4,REWRITE1:15;
    then BetaSigmaRed(V) reduces A, A2 by C3,REWRITE1:16;
    hence thesis by C4;
  end;
  B2: for a,b being object st BetaSigmaRed(V) reduces a,b & P[a] holds P[b]
    from ENVKEY:sch 1(B1);
  assume B3: BetaSigmaRed(V) reduces eEps A, Q;
  BetaSigmaRed(V) reduces A, A by REWRITE1:12;
  then P[eEps A];
  hence thesis by B2,B3;
end;

begin :: Preimages of an environment application

theorem Th3:
  for M being EnvEpsTerm of V, X,Y being FrEnvTerm of V
  st tr M = fApp(fEps X, Y)
  ex A,B being EnvEpsTerm of V st BetaSigmaRed(V) reduces M, eComp(A,B) &
    tr A = X & tr B = Y
proof
  let M be EnvEpsTerm of V, X,Y be FrEnvTerm of V;
  assume A0: tr M = fApp(fEps X, Y);
  per cases by A0,FRENV_3:20;
  suppose ex A,B being EnvEpsTerm of V st M = eApp(A,B) & tr A = fEps X &
      tr B = Y;
    then consider A,B being EnvEpsTerm of V such that
    B1: M = eApp(A,B) & tr A = fEps X & tr B = Y;
    consider A1 being EnvEpsTerm of V such that
    B2: A = eEps A1 & tr A1 = X by B1,FRENV_3:18;
    take A1, B;
    [eApp(eEps A1,B), eComp(A1,B)] in BetaSigmaRed(V) by ENVBETA:37;
    hence BetaSigmaRed(V) reduces M, eComp(A1,B) by B1,B2,REWRITE1:15;
    thus tr A1 = X & tr B = Y by B1,B2;
  end;
  suppose ex A,B being EnvEpsTerm of V st M = eComp(A,B) &
      fEps (tr A) = fEps X & tr B = Y;
    then consider A,B being EnvEpsTerm of V such that
    B1: M = eComp(A,B) & fEps (tr A) = fEps X & tr B = Y;
    take A, B;
    thus BetaSigmaRed(V) reduces M, eComp(A,B) by B1,REWRITE1:12;
    thus tr A = X & tr B = Y by B1,FRENV_1:12;
  end;
end;

begin :: Single-step lifting

theorem Th4:
  for P,Q being FrEnvTerm of V st [P,Q] in FrRed(V)
  for M being EnvEpsTerm of V st tr M = P
  ex N,L being EnvEpsTerm of V st tr N = Q &
    BetaSigmaRed(V) reduces N,L & BetaSigmaRed(V) reduces M,L
proof
  set FG = FrEnvGram(V);
  defpred Lf[object,object] means
    for M being EnvEpsTerm of V st tr M = $1
    ex N,L being EnvEpsTerm of V st tr N = $2 &
      BetaSigmaRed(V) reduces N,L & BetaSigmaRed(V) reduces M,L;
  set K = { z where z is Element of [:TS FG, TS FG:] :
    ex P,Q being FrEnvTerm of V st z = [P,Q] & Lf[P,Q] };
  A1: K c= [:TS FG, TS FG:]
  proof
    let u be object;
    assume u in K;
    then ex z being Element of [:TS FG, TS FG:] st u = z &
      ex P,Q being FrEnvTerm of V st z = [P,Q] & Lf[P,Q];
    hence thesis;
  end;
  reconsider K1 = K as Relation of TS FG by A1;
  A2: for a,b being FrEnvTerm of V holds ( [a,b] in K1 iff Lf[a,b] )
  proof
    let a,b be FrEnvTerm of V;
    hereby
      assume [a,b] in K1;
      then consider z being Element of [:TS FG, TS FG:] such that
      B1: [a,b] = z and
      B2: ex P,Q being FrEnvTerm of V st z = [P,Q] & Lf[P,Q];
      consider P,Q being FrEnvTerm of V such that
      B3: z = [P,Q] & Lf[P,Q] by B2;
      a = P & b = Q by B1,B3,XTUPLE_0:1;
      hence Lf[a,b] by B3;
    end;
    assume C1: Lf[a,b];
    [a,b] in [:TS FG, TS FG:] by ZFMISC_1:87;
    then reconsider z = [a,b] as Element of [:TS FG, TS FG:];
    ex P,Q being FrEnvTerm of V st z = [P,Q] & Lf[P,Q] by C1;
    hence thesis;
  end;
  A3: K1 is bs-closed
  proof
    thus for A,B being FrEnvTerm of V, x being Element of V holds
      [fApp(fLam(x,A),B), fApp(fEps A, fExt(B,x,fId V))] in K1
    proof
      let A,B be FrEnvTerm of V, x be Element of V;
      C0: Lf[fApp(fLam(x,A),B), fApp(fEps A, fExt(B,x,fId V))]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fApp(fLam(x,A),B);
        per cases by D0,FRENV_3:20;
        suppose ex A0,B0 being EnvEpsTerm of V st M = eApp(A0,B0) &
            tr A0 = fLam(x,A) & tr B0 = B;
          then consider A0,B0 being EnvEpsTerm of V such that
          E1: M = eApp(A0,B0) & tr A0 = fLam(x,A) & tr B0 = B;
          consider C being EnvEpsTerm of V such that
          E2: A0 = eLam(x,C) & tr C = A by E1,FRENV_3:17;
          take eComp(C, eExt(B0,x,eId V)), eComp(C, eExt(B0,x,eId V));
          thus tr (eComp(C, eExt(B0,x,eId V)))
              = fApp(fEps (tr C), tr (eExt(B0,x,eId V))) by FRENV_3:13
            .= fApp(fEps A, fExt(tr B0, x, tr (eId V))) by E2,FRENV_3:12
            .= fApp(fEps A, fExt(B, x, fId V)) by E1,FRENV_4:1;
          thus BetaSigmaRed(V) reduces eComp(C, eExt(B0,x,eId V)),
            eComp(C, eExt(B0,x,eId V)) by REWRITE1:12;
          [eApp(eLam(x,C),B0), eComp(C,eExt(B0,x,eId V))]
            in BetaSigmaRed(V) by ENVBETA:35;
          hence thesis by E1,E2,REWRITE1:15;
        end;
        suppose ex A0,B0 being EnvEpsTerm of V st M = eComp(A0,B0) &
            fEps (tr A0) = fLam(x,A) & tr B0 = B;
          then consider A0,B0 being EnvEpsTerm of V such that
          E1: M = eComp(A0,B0) & fEps (tr A0) = fLam(x,A) & tr B0 = B;
          thus thesis by E1,FRENV_1:17;
        end;
      end;
      thus thesis by A2,C0;
    end;
    thus for A,B,L being FrEnvTerm of V, x being Element of V holds
      [fApp(fApp(fEps (fLam(x,A)),L),B), fApp(fEps A, fExt(B,x,L))] in K1
    proof
      let A,B,L be FrEnvTerm of V, x be Element of V;
      C0: Lf[fApp(fApp(fEps (fLam(x,A)),L),B), fApp(fEps A, fExt(B,x,L))]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fApp(fApp(fEps (fLam(x,A)),L),B);
        per cases by D0,FRENV_3:20;
        suppose ex A0,B0 being EnvEpsTerm of V st M = eApp(A0,B0) &
            tr A0 = fApp(fEps (fLam(x,A)),L) & tr B0 = B;
          then consider A0,B0 being EnvEpsTerm of V such that
          E1: M = eApp(A0,B0) & tr A0 = fApp(fEps (fLam(x,A)),L) & tr B0 = B;
          consider D,E being EnvEpsTerm of V such that
          E2: BetaSigmaRed(V) reduces A0, eComp(D,E) & tr D = fLam(x,A) &
            tr E = L by E1,Th3;
          consider C being EnvEpsTerm of V such that
          E3: D = eLam(x,C) & tr C = A by E2,FRENV_3:17;
          take eComp(C, eExt(B0,x,E)), eComp(C, eExt(B0,x,E));
          thus tr (eComp(C, eExt(B0,x,E)))
              = fApp(fEps (tr C), tr (eExt(B0,x,E))) by FRENV_3:13
            .= fApp(fEps A, fExt(tr B0, x, tr E)) by E3,FRENV_3:12
            .= fApp(fEps A, fExt(B, x, L)) by E1,E2;
          thus BetaSigmaRed(V) reduces eComp(C, eExt(B0,x,E)),
            eComp(C, eExt(B0,x,E)) by REWRITE1:12;
          E4: BetaSigmaRed(V) reduces eApp(A0,B0),
            eApp(eComp(eLam(x,C),E),B0) by E2,E3,ENVBETA:54;
          [eApp(eComp(eLam(x,C),E),B0), eComp(C,eExt(B0,x,E))]
            in BetaSigmaRed(V) by ENVBETA:36;
          then BetaSigmaRed(V) reduces eApp(eComp(eLam(x,C),E),B0),
            eComp(C,eExt(B0,x,E)) by REWRITE1:15;
          hence thesis by E1,E4,REWRITE1:16;
        end;
        suppose ex A0,B0 being EnvEpsTerm of V st M = eComp(A0,B0) &
            fEps (tr A0) = fApp(fEps (fLam(x,A)),L) & tr B0 = B;
          then consider A0,B0 being EnvEpsTerm of V such that
          E1: M = eComp(A0,B0) &
            fEps (tr A0) = fApp(fEps (fLam(x,A)),L) & tr B0 = B;
          thus thesis by E1,FRENV_1:17;
        end;
      end;
      thus thesis by A2,C0;
    end;
    thus for A,B being FrEnvTerm of V holds
      [fApp(fEps (fEps A),B), fEps A] in K1
    proof
      let A,B be FrEnvTerm of V;
      C0: Lf[fApp(fEps (fEps A),B), fEps A]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fApp(fEps (fEps A),B);
        consider D,E being EnvEpsTerm of V such that
        E1: BetaSigmaRed(V) reduces M, eComp(D,E) & tr D = fEps A &
          tr E = B by D0,Th3;
        consider C being EnvEpsTerm of V such that
        E2: D = eEps C & tr C = A by E1,FRENV_3:18;
        take eEps C, eEps C;
        thus tr (eEps C) = fEps A by E2,FRENV_3:10;
        thus BetaSigmaRed(V) reduces eEps C, eEps C by REWRITE1:12;
        [eComp(eEps C,E), eEps C] in BetaSigmaRed(V) by ENVBETA:45;
        then BetaSigmaRed(V) reduces eComp(eEps C,E), eEps C by REWRITE1:15;
        hence thesis by E1,E2,REWRITE1:16;
      end;
      thus thesis by A2,C0;
    end;
    thus for L,A,B being FrEnvTerm of V holds
      [fApp(fEps (fApp(fEps L,A)),B), fApp(fEps L, fApp(fEps A,B))] in K1
    proof
      let L,A,B be FrEnvTerm of V;
      C0: Lf[fApp(fEps (fApp(fEps L,A)),B), fApp(fEps L, fApp(fEps A,B))]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fApp(fEps (fApp(fEps L,A)),B);
        consider D,E being EnvEpsTerm of V such that
        E1: BetaSigmaRed(V) reduces M, eComp(D,E) & tr D = fApp(fEps L,A) &
          tr E = B by D0,Th3;
        consider C,C2 being EnvEpsTerm of V such that
        E2: BetaSigmaRed(V) reduces D, eComp(C,C2) & tr C = L & tr C2 = A
          by E1,Th3;
        take eComp(C, eComp(C2,E)), eComp(C, eComp(C2,E));
        thus tr (eComp(C, eComp(C2,E)))
            = fApp(fEps (tr C), tr (eComp(C2,E))) by FRENV_3:13
          .= fApp(fEps L, fApp(fEps (tr C2), tr E)) by E2,FRENV_3:13
          .= fApp(fEps L, fApp(fEps A, B)) by E1,E2;
        thus BetaSigmaRed(V) reduces eComp(C, eComp(C2,E)),
          eComp(C, eComp(C2,E)) by REWRITE1:12;
        E3: BetaSigmaRed(V) reduces eComp(D,E), eComp(eComp(C,C2),E)
          by E2,ENVBETA:59;
        [eComp(eComp(C,C2),E), eComp(C,eComp(C2,E))] in BetaSigmaRed(V)
          by ENVBETA:38;
        then BetaSigmaRed(V) reduces eComp(eComp(C,C2),E),
          eComp(C,eComp(C2,E)) by REWRITE1:15;
        then BetaSigmaRed(V) reduces eComp(D,E), eComp(C,eComp(C2,E))
          by E3,REWRITE1:16;
        hence thesis by E1,REWRITE1:16;
      end;
      thus thesis by A2,C0;
    end;
    thus for A being FrEnvTerm of V holds [fApp(fEps (fId V),A), A] in K1
    proof
      let A be FrEnvTerm of V;
      C0: Lf[fApp(fEps (fId V),A), A]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fApp(fEps (fId V),A);
        consider D,E being EnvEpsTerm of V such that
        E1: BetaSigmaRed(V) reduces M, eComp(D,E) & tr D = fId V & tr E = A
          by D0,Th3;
        E2: D = eId V by E1,FRENV_3:16;
        take E, E;
        thus tr E = A by E1;
        thus BetaSigmaRed(V) reduces E, E by REWRITE1:12;
        [eComp(eId V,E), E] in BetaSigmaRed(V) by ENVBETA:39;
        then BetaSigmaRed(V) reduces eComp(D,E), E by E2,REWRITE1:15;
        hence thesis by E1,REWRITE1:16;
      end;
      thus thesis by A2,C0;
    end;
    thus for A being FrEnvTerm of V holds [fApp(fEps A, fId V), A] in K1
    proof
      let A be FrEnvTerm of V;
      C0: Lf[fApp(fEps A, fId V), A]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fApp(fEps A, fId V);
        consider D,E being EnvEpsTerm of V such that
        E1: BetaSigmaRed(V) reduces M, eComp(D,E) & tr D = A &
          tr E = fId V by D0,Th3;
        E2: E = eId V by E1,FRENV_3:16;
        take D, D;
        thus tr D = A by E1;
        thus BetaSigmaRed(V) reduces D, D by REWRITE1:12;
        [eComp(D,eId V), D] in BetaSigmaRed(V) by ENVBETA:40;
        then BetaSigmaRed(V) reduces eComp(D,E), D by E2,REWRITE1:15;
        hence thesis by E1,REWRITE1:16;
      end;
      thus thesis by A2,C0;
    end;
    thus for L,A,B being FrEnvTerm of V, x being Element of V holds
      [fApp(fEps (fExt(L,x,A)),B),
        fExt(fApp(fEps L,B),x,fApp(fEps A,B))] in K1
    proof
      let L,A,B be FrEnvTerm of V, x be Element of V;
      C0: Lf[fApp(fEps (fExt(L,x,A)),B),
        fExt(fApp(fEps L,B),x,fApp(fEps A,B))]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fApp(fEps (fExt(L,x,A)),B);
        consider D,E being EnvEpsTerm of V such that
        E1: BetaSigmaRed(V) reduces M, eComp(D,E) & tr D = fExt(L,x,A) &
          tr E = B by D0,Th3;
        consider C,C2 being EnvEpsTerm of V such that
        E2: D = eExt(C,x,C2) & tr C = L & tr C2 = A by E1,FRENV_3:19;
        take eExt(eComp(C,E),x,eComp(C2,E)), eExt(eComp(C,E),x,eComp(C2,E));
        thus tr (eExt(eComp(C,E),x,eComp(C2,E)))
            = fExt(tr (eComp(C,E)), x, tr (eComp(C2,E))) by FRENV_3:12
          .= fExt(fApp(fEps (tr C), tr E), x, tr (eComp(C2,E)))
             by FRENV_3:13
          .= fExt(fApp(fEps L, B), x, fApp(fEps (tr C2), tr E))
             by E1,E2,FRENV_3:13
          .= fExt(fApp(fEps L, B), x, fApp(fEps A, B)) by E1,E2;
        thus BetaSigmaRed(V) reduces eExt(eComp(C,E),x,eComp(C2,E)),
          eExt(eComp(C,E),x,eComp(C2,E)) by REWRITE1:12;
        [eComp(eExt(C,x,C2),E), eExt(eComp(C,E),x,eComp(C2,E))]
          in BetaSigmaRed(V) by ENVBETA:41;
        then BetaSigmaRed(V) reduces eComp(D,E),
          eExt(eComp(C,E),x,eComp(C2,E)) by E2,REWRITE1:15;
        hence thesis by E1,REWRITE1:16;
      end;
      thus thesis by A2,C0;
    end;
    thus for A,B being FrEnvTerm of V, x being Element of V holds
      [fApp(fEps (fVar x), fExt(A,x,B)), A] in K1
    proof
      let A,B be FrEnvTerm of V, x be Element of V;
      C0: Lf[fApp(fEps (fVar x), fExt(A,x,B)), A]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fApp(fEps (fVar x), fExt(A,x,B));
        consider D,E being EnvEpsTerm of V such that
        E1: BetaSigmaRed(V) reduces M, eComp(D,E) & tr D = fVar x &
          tr E = fExt(A,x,B) by D0,Th3;
        E2: D = eVar x by E1,FRENV_3:15;
        consider C,C2 being EnvEpsTerm of V such that
        E3: E = eExt(C,x,C2) & tr C = A & tr C2 = B by E1,FRENV_3:19;
        take C, C;
        thus tr C = A by E3;
        thus BetaSigmaRed(V) reduces C, C by REWRITE1:12;
        [eComp(eVar x, eExt(C,x,C2)), C] in BetaSigmaRed(V) by ENVBETA:42;
        then BetaSigmaRed(V) reduces eComp(D,E), C by E2,E3,REWRITE1:15;
        hence thesis by E1,REWRITE1:16;
      end;
      thus thesis by A2,C0;
    end;
    thus for A,B being FrEnvTerm of V, x,y being Element of V st x <> y
      holds [fApp(fEps (fVar y), fExt(A,x,B)), fApp(fEps (fVar y), B)] in K1
    proof
      let A,B be FrEnvTerm of V, x,y be Element of V;
      assume CX: x <> y;
      C0: Lf[fApp(fEps (fVar y), fExt(A,x,B)), fApp(fEps (fVar y), B)]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fApp(fEps (fVar y), fExt(A,x,B));
        consider D,E being EnvEpsTerm of V such that
        E1: BetaSigmaRed(V) reduces M, eComp(D,E) & tr D = fVar y &
          tr E = fExt(A,x,B) by D0,Th3;
        E2: D = eVar y by E1,FRENV_3:15;
        consider C,C2 being EnvEpsTerm of V such that
        E3: E = eExt(C,x,C2) & tr C = A & tr C2 = B by E1,FRENV_3:19;
        take eComp(eVar y, C2), eComp(eVar y, C2);
        thus tr (eComp(eVar y, C2))
            = fApp(fEps (tr (eVar y)), tr C2) by FRENV_3:13
          .= fApp(fEps (fVar y), tr C2) by FRENV_3:8
          .= fApp(fEps (fVar y), B) by E3;
        thus BetaSigmaRed(V) reduces eComp(eVar y, C2), eComp(eVar y, C2)
          by REWRITE1:12;
        [eComp(eVar y, eExt(C,x,C2)), eComp(eVar y, C2)] in BetaSigmaRed(V)
          by CX,ENVBETA:43;
        then BetaSigmaRed(V) reduces eComp(D,E), eComp(eVar y, C2)
          by E2,E3,REWRITE1:15;
        hence thesis by E1,REWRITE1:16;
      end;
      thus thesis by A2,C0;
    end;
    thus for A,B,L being FrEnvTerm of V holds
      [fApp(fEps (fApp(A,B)),L), fApp(fApp(fEps A,L), fApp(fEps B,L))] in K1
    proof
      let A,B,L be FrEnvTerm of V;
      C0: Lf[fApp(fEps (fApp(A,B)),L),
        fApp(fApp(fEps A,L), fApp(fEps B,L))]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fApp(fEps (fApp(A,B)),L);
        consider D,E being EnvEpsTerm of V such that
        E1: BetaSigmaRed(V) reduces M, eComp(D,E) & tr D = fApp(A,B) &
          tr E = L by D0,Th3;
        per cases by E1,FRENV_3:20;
        suppose ex C,C2 being EnvEpsTerm of V st D = eApp(C,C2) &
            tr C = A & tr C2 = B;
          then consider C,C2 being EnvEpsTerm of V such that
          F1: D = eApp(C,C2) & tr C = A & tr C2 = B;
          take eApp(eComp(C,E),eComp(C2,E)), eApp(eComp(C,E),eComp(C2,E));
          thus tr (eApp(eComp(C,E),eComp(C2,E)))
              = fApp(tr (eComp(C,E)), tr (eComp(C2,E))) by FRENV_3:11
            .= fApp(fApp(fEps (tr C), tr E), tr (eComp(C2,E))) by FRENV_3:13
            .= fApp(fApp(fEps A, L), fApp(fEps (tr C2), tr E))
               by E1,F1,FRENV_3:13
            .= fApp(fApp(fEps A, L), fApp(fEps B, L)) by E1,F1;
          thus BetaSigmaRed(V) reduces eApp(eComp(C,E),eComp(C2,E)),
            eApp(eComp(C,E),eComp(C2,E)) by REWRITE1:12;
          [eComp(eApp(C,C2),E), eApp(eComp(C,E),eComp(C2,E))]
            in BetaSigmaRed(V) by ENVBETA:44;
          then BetaSigmaRed(V) reduces eComp(D,E),
            eApp(eComp(C,E),eComp(C2,E)) by F1,REWRITE1:15;
          hence thesis by E1,REWRITE1:16;
        end;
        suppose ex C,C2 being EnvEpsTerm of V st D = eComp(C,C2) &
            fEps (tr C) = A & tr C2 = B;
          then consider C,C2 being EnvEpsTerm of V such that
          F1: D = eComp(C,C2) & fEps (tr C) = A & tr C2 = B;
          take eApp(eComp(eEps C,E),eComp(C2,E)), eComp(C,eComp(C2,E));
          thus tr (eApp(eComp(eEps C,E),eComp(C2,E)))
              = fApp(tr (eComp(eEps C,E)), tr (eComp(C2,E))) by FRENV_3:11
            .= fApp(fApp(fEps (tr (eEps C)), tr E), tr (eComp(C2,E)))
               by FRENV_3:13
            .= fApp(fApp(fEps (fEps (tr C)), tr E), tr (eComp(C2,E)))
               by FRENV_3:10
            .= fApp(fApp(fEps A, L), fApp(fEps (tr C2), tr E))
               by E1,F1,FRENV_3:13
            .= fApp(fApp(fEps A, L), fApp(fEps B, L)) by E1,F1;
          [eComp(eEps C,E), eEps C] in BetaSigmaRed(V) by ENVBETA:45;
          then BetaSigmaRed(V) reduces eComp(eEps C,E), eEps C
            by REWRITE1:15;
          then F2: BetaSigmaRed(V) reduces eApp(eComp(eEps C,E),eComp(C2,E)),
            eApp(eEps C, eComp(C2,E)) by ENVBETA:54;
          [eApp(eEps C, eComp(C2,E)), eComp(C, eComp(C2,E))]
            in BetaSigmaRed(V) by ENVBETA:37;
          then BetaSigmaRed(V) reduces eApp(eEps C, eComp(C2,E)),
            eComp(C, eComp(C2,E)) by REWRITE1:15;
          hence BetaSigmaRed(V) reduces eApp(eComp(eEps C,E),eComp(C2,E)),
            eComp(C, eComp(C2,E)) by F2,REWRITE1:16;
          [eComp(eComp(C,C2),E), eComp(C,eComp(C2,E))] in BetaSigmaRed(V)
            by ENVBETA:38;
          then BetaSigmaRed(V) reduces eComp(D,E), eComp(C,eComp(C2,E))
            by F1,REWRITE1:15;
          hence thesis by E1,REWRITE1:16;
        end;
      end;
      thus thesis by A2,C0;
    end;
    thus for A,A1,B being FrEnvTerm of V st [A,A1] in K1 holds
      [fApp(A,B), fApp(A1,B)] in K1
    proof
      let A,A1,B be FrEnvTerm of V;
      assume [A,A1] in K1;
      then CI: Lf[A,A1] by A2;
      C0: Lf[fApp(A,B), fApp(A1,B)]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fApp(A,B);
        per cases by D0,FRENV_3:20;
        suppose ex C,C2 being EnvEpsTerm of V st M = eApp(C,C2) &
            tr C = A & tr C2 = B;
          then consider C,C2 being EnvEpsTerm of V such that
          F1: M = eApp(C,C2) & tr C = A & tr C2 = B;
          consider N0,L0 being EnvEpsTerm of V such that
          F2: tr N0 = A1 & BetaSigmaRed(V) reduces N0,L0 &
            BetaSigmaRed(V) reduces C,L0 by CI,F1;
          take eApp(N0,C2), eApp(L0,C2);
          thus tr (eApp(N0,C2)) = fApp(tr N0, tr C2) by FRENV_3:11
            .= fApp(A1,B) by F1,F2;
          thus BetaSigmaRed(V) reduces eApp(N0,C2), eApp(L0,C2)
            by F2,ENVBETA:54;
          thus thesis by F1,F2,ENVBETA:54;
        end;
        suppose ex C,C2 being EnvEpsTerm of V st M = eComp(C,C2) &
            fEps (tr C) = A & tr C2 = B;
          then consider C,C2 being EnvEpsTerm of V such that
          F1: M = eComp(C,C2) & fEps (tr C) = A & tr C2 = B;
          F2: tr (eEps C) = A by F1,FRENV_3:10;
          consider N0,L0 being EnvEpsTerm of V such that
          F3: tr N0 = A1 & BetaSigmaRed(V) reduces N0,L0 &
            BetaSigmaRed(V) reduces eEps C, L0 by CI,F2;
          consider C3 being EnvEpsTerm of V such that
          F4: L0 = eEps C3 & BetaSigmaRed(V) reduces C, C3 by F3,Th2;
          take eApp(N0,C2), eComp(C3,C2);
          thus tr (eApp(N0,C2)) = fApp(tr N0, tr C2) by FRENV_3:11
            .= fApp(A1,B) by F1,F3;
          F5: BetaSigmaRed(V) reduces eApp(N0,C2), eApp(eEps C3, C2)
            by F3,F4,ENVBETA:54;
          [eApp(eEps C3,C2), eComp(C3,C2)] in BetaSigmaRed(V)
            by ENVBETA:37;
          then BetaSigmaRed(V) reduces eApp(eEps C3,C2), eComp(C3,C2)
            by REWRITE1:15;
          hence BetaSigmaRed(V) reduces eApp(N0,C2), eComp(C3,C2)
            by F5,REWRITE1:16;
          thus thesis by F1,F4,ENVBETA:59;
        end;
      end;
      thus thesis by A2,C0;
    end;
    thus for A,B,B1 being FrEnvTerm of V st [B,B1] in K1 holds
      [fApp(A,B), fApp(A,B1)] in K1
    proof
      let A,B,B1 be FrEnvTerm of V;
      assume [B,B1] in K1;
      then CI: Lf[B,B1] by A2;
      C0: Lf[fApp(A,B), fApp(A,B1)]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fApp(A,B);
        per cases by D0,FRENV_3:20;
        suppose ex C,C2 being EnvEpsTerm of V st M = eApp(C,C2) &
            tr C = A & tr C2 = B;
          then consider C,C2 being EnvEpsTerm of V such that
          F1: M = eApp(C,C2) & tr C = A & tr C2 = B;
          consider N0,L0 being EnvEpsTerm of V such that
          F2: tr N0 = B1 & BetaSigmaRed(V) reduces N0,L0 &
            BetaSigmaRed(V) reduces C2,L0 by CI,F1;
          take eApp(C,N0), eApp(C,L0);
          thus tr (eApp(C,N0)) = fApp(tr C, tr N0) by FRENV_3:11
            .= fApp(A,B1) by F1,F2;
          thus BetaSigmaRed(V) reduces eApp(C,N0), eApp(C,L0)
            by F2,ENVBETA:55;
          thus thesis by F1,F2,ENVBETA:55;
        end;
        suppose ex C,C2 being EnvEpsTerm of V st M = eComp(C,C2) &
            fEps (tr C) = A & tr C2 = B;
          then consider C,C2 being EnvEpsTerm of V such that
          F1: M = eComp(C,C2) & fEps (tr C) = A & tr C2 = B;
          consider N0,L0 being EnvEpsTerm of V such that
          F2: tr N0 = B1 & BetaSigmaRed(V) reduces N0,L0 &
            BetaSigmaRed(V) reduces C2,L0 by CI,F1;
          take eComp(C,N0), eComp(C,L0);
          thus tr (eComp(C,N0)) = fApp(fEps (tr C), tr N0) by FRENV_3:13
            .= fApp(A,B1) by F1,F2;
          thus BetaSigmaRed(V) reduces eComp(C,N0), eComp(C,L0)
            by F2,ENVBETA:60;
          thus thesis by F1,F2,ENVBETA:60;
        end;
      end;
      thus thesis by A2,C0;
    end;
    thus for A,A1 being FrEnvTerm of V, x being Element of V st [A,A1] in K1
      holds [fLam(x,A), fLam(x,A1)] in K1
    proof
      let A,A1 be FrEnvTerm of V, x be Element of V;
      assume [A,A1] in K1;
      then CI: Lf[A,A1] by A2;
      C0: Lf[fLam(x,A), fLam(x,A1)]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fLam(x,A);
        consider C being EnvEpsTerm of V such that
        F1: M = eLam(x,C) & tr C = A by D0,FRENV_3:17;
        consider N0,L0 being EnvEpsTerm of V such that
        F2: tr N0 = A1 & BetaSigmaRed(V) reduces N0,L0 &
          BetaSigmaRed(V) reduces C,L0 by CI,F1;
        take eLam(x,N0), eLam(x,L0);
        thus tr (eLam(x,N0)) = fLam(x, tr N0) by FRENV_3:9
          .= fLam(x,A1) by F2;
        thus BetaSigmaRed(V) reduces eLam(x,N0), eLam(x,L0)
          by F2,ENVBETA:56;
        thus thesis by F1,F2,ENVBETA:56;
      end;
      thus thesis by A2,C0;
    end;
    thus for A,A1,B being FrEnvTerm of V, x being Element of V
      st [A,A1] in K1 holds [fExt(A,x,B), fExt(A1,x,B)] in K1
    proof
      let A,A1,B be FrEnvTerm of V, x be Element of V;
      assume [A,A1] in K1;
      then CI: Lf[A,A1] by A2;
      C0: Lf[fExt(A,x,B), fExt(A1,x,B)]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fExt(A,x,B);
        consider C,C2 being EnvEpsTerm of V such that
        F1: M = eExt(C,x,C2) & tr C = A & tr C2 = B by D0,FRENV_3:19;
        consider N0,L0 being EnvEpsTerm of V such that
        F2: tr N0 = A1 & BetaSigmaRed(V) reduces N0,L0 &
          BetaSigmaRed(V) reduces C,L0 by CI,F1;
        take eExt(N0,x,C2), eExt(L0,x,C2);
        thus tr (eExt(N0,x,C2)) = fExt(tr N0, x, tr C2) by FRENV_3:12
          .= fExt(A1,x,B) by F1,F2;
        thus BetaSigmaRed(V) reduces eExt(N0,x,C2), eExt(L0,x,C2)
          by F2,ENVBETA:57;
        thus thesis by F1,F2,ENVBETA:57;
      end;
      thus thesis by A2,C0;
    end;
    thus for A,B,B1 being FrEnvTerm of V, x being Element of V
      st [B,B1] in K1 holds [fExt(A,x,B), fExt(A,x,B1)] in K1
    proof
      let A,B,B1 be FrEnvTerm of V, x be Element of V;
      assume [B,B1] in K1;
      then CI: Lf[B,B1] by A2;
      C0: Lf[fExt(A,x,B), fExt(A,x,B1)]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fExt(A,x,B);
        consider C,C2 being EnvEpsTerm of V such that
        F1: M = eExt(C,x,C2) & tr C = A & tr C2 = B by D0,FRENV_3:19;
        consider N0,L0 being EnvEpsTerm of V such that
        F2: tr N0 = B1 & BetaSigmaRed(V) reduces N0,L0 &
          BetaSigmaRed(V) reduces C2,L0 by CI,F1;
        take eExt(C,x,N0), eExt(C,x,L0);
        thus tr (eExt(C,x,N0)) = fExt(tr C, x, tr N0) by FRENV_3:12
          .= fExt(A,x,B1) by F1,F2;
        thus BetaSigmaRed(V) reduces eExt(C,x,N0), eExt(C,x,L0)
          by F2,ENVBETA:58;
        thus thesis by F1,F2,ENVBETA:58;
      end;
      thus thesis by A2,C0;
    end;
    thus for A,A1 being FrEnvTerm of V st [A,A1] in K1 holds
      [fEps A, fEps A1] in K1
    proof
      let A,A1 be FrEnvTerm of V;
      assume [A,A1] in K1;
      then CI: Lf[A,A1] by A2;
      C0: Lf[fEps A, fEps A1]
      proof
        let M be EnvEpsTerm of V;
        assume D0: tr M = fEps A;
        consider C being EnvEpsTerm of V such that
        F1: M = eEps C & tr C = A by D0,FRENV_3:18;
        consider N0,L0 being EnvEpsTerm of V such that
        F2: tr N0 = A1 & BetaSigmaRed(V) reduces N0,L0 &
          BetaSigmaRed(V) reduces C,L0 by CI,F1;
        take eEps N0, eEps L0;
        thus tr (eEps N0) = fEps (tr N0) by FRENV_3:10
          .= fEps A1 by F2;
        thus BetaSigmaRed(V) reduces eEps N0, eEps L0 by F2,ENVBETA:61;
        thus thesis by F1,F2,ENVBETA:61;
      end;
      thus thesis by A2,C0;
    end;
  end;
  A4: FrRed(V) c= K1 by A3,FRENV_2:2;
  let P,Q be FrEnvTerm of V;
  assume [P,Q] in FrRed(V);
  then [P,Q] in K1 by A4;
  hence thesis by A2;
end;

begin :: Multi-step lifting and confluence

theorem Th5:
  for P,Q being FrEnvTerm of V st FrRed(V) reduces P,Q
  for M being EnvEpsTerm of V st tr M = P
  ex N,L being EnvEpsTerm of V st tr N = Q &
    BetaSigmaRed(V) reduces N,L & BetaSigmaRed(V) reduces M,L
proof
  let P,Q be FrEnvTerm of V;
  set FG = FrEnvGram(V);
  assume A0: FrRed(V) reduces P,Q;
  defpred R[object] means ex Q1 being FrEnvTerm of V st Q1 = $1 &
    for M being EnvEpsTerm of V st tr M = P
    ex N,L being EnvEpsTerm of V st tr N = Q1 &
      BetaSigmaRed(V) reduces N,L & BetaSigmaRed(V) reduces M,L;
  A1: for a,b being object st R[a] & [a,b] in FrRed(V) holds R[b]
  proof
    let a,b be object;
    assume that B1: R[a] and B2: [a,b] in FrRed(V);
    consider Q1 being FrEnvTerm of V such that
    B3: Q1 = a and
    B4: for M being EnvEpsTerm of V st tr M = P
      ex N,L being EnvEpsTerm of V st tr N = Q1 &
        BetaSigmaRed(V) reduces N,L & BetaSigmaRed(V) reduces M,L by B1;
    FrRed(V) c= [:TS FG, TS FG:];
    then [a,b] in [:TS FG, TS FG:] by B2;
    then b in TS FG by ZFMISC_1:87;
    then reconsider b1 = b as FrEnvTerm of V;
    B5: [Q1,b1] in FrRed(V) by B2,B3;
    now
      let M be EnvEpsTerm of V;
      assume C0: tr M = P;
      consider N0,L0 being EnvEpsTerm of V such that
      C1: tr N0 = Q1 & BetaSigmaRed(V) reduces N0,L0 &
        BetaSigmaRed(V) reduces M,L0 by B4,C0;
      consider N1,L1 being EnvEpsTerm of V such that
      C2: tr N1 = b1 & BetaSigmaRed(V) reduces N1,L1 &
        BetaSigmaRed(V) reduces N0,L1 by B5,C1,Th4;
      consider L2 being EnvEpsTerm of V such that
      C3: BetaSigmaRed(V) reduces L0,L2 & BetaSigmaRed(V) reduces L1,L2
        by C1,C2,ENVCONF:12;
      take N1, L2;
      thus tr N1 = b1 by C2;
      thus BetaSigmaRed(V) reduces N1,L2 by C2,C3,REWRITE1:16;
      thus BetaSigmaRed(V) reduces M,L2 by C1,C3,REWRITE1:16;
    end;
    hence thesis;
  end;
  A2: for a,b being object st FrRed(V) reduces a,b & R[a] holds R[b]
    from ENVKEY:sch 1(A1);
  B0: for M being EnvEpsTerm of V st tr M = P
    ex N,L being EnvEpsTerm of V st tr N = P &
      BetaSigmaRed(V) reduces N,L & BetaSigmaRed(V) reduces M,L
  proof
    let M be EnvEpsTerm of V;
    assume B1: tr M = P;
    take M, M;
    thus tr M = P by B1;
    thus BetaSigmaRed(V) reduces M,M by REWRITE1:12;
    thus BetaSigmaRed(V) reduces M,M by REWRITE1:12;
  end;
  R[P]
  proof
    take P;
    thus P = P;
    thus for M being EnvEpsTerm of V st tr M = P
      ex N,L being EnvEpsTerm of V st tr N = P &
        BetaSigmaRed(V) reduces N,L & BetaSigmaRed(V) reduces M,L by B0;
  end;
  then R[Q] by A0,A2;
  then consider Q1 being FrEnvTerm of V such that
  A3: Q1 = Q and
  A4: for M being EnvEpsTerm of V st tr M = P
    ex N,L being EnvEpsTerm of V st tr N = Q1 &
      BetaSigmaRed(V) reduces N,L & BetaSigmaRed(V) reduces M,L;
  thus thesis by A3,A4;
end;

theorem Th6:
  for P,Q1,Q2 being FrEnvTerm of V
  st FrRed(V) reduces P,Q1 & FrRed(V) reduces P,Q2
  ex Q being FrEnvTerm of V st
    FrRed(V) reduces Q1,Q & FrRed(V) reduces Q2,Q
proof
  let P,Q1,Q2 be FrEnvTerm of V;
  assume A0: FrRed(V) reduces P,Q1 & FrRed(V) reduces P,Q2;
  consider P0 being EnvEpsTerm of V such that
  A1: tr P0 = P by FRENV_3:14;
  consider N1,L1 being EnvEpsTerm of V such that
  A2: tr N1 = Q1 & BetaSigmaRed(V) reduces N1,L1 &
    BetaSigmaRed(V) reduces P0,L1 by A0,A1,Th5;
  consider N2,L2 being EnvEpsTerm of V such that
  A3: tr N2 = Q2 & BetaSigmaRed(V) reduces N2,L2 &
    BetaSigmaRed(V) reduces P0,L2 by A0,A1,Th5;
  consider L being EnvEpsTerm of V such that
  A4: BetaSigmaRed(V) reduces L1,L & BetaSigmaRed(V) reduces L2,L
    by A2,A3,ENVCONF:12;
  take tr L;
  BetaSigmaRed(V) reduces N1,L by A2,A4,REWRITE1:16;
  hence FrRed(V) reduces Q1, tr L by A2,FRENV_4:3;
  BetaSigmaRed(V) reduces N2,L by A3,A4,REWRITE1:16;
  hence FrRed(V) reduces Q2, tr L by A3,FRENV_4:3;
end;

theorem Th7:
  for A being FrEnvTerm of V, d being object
  for R being Relation of TS(FrEnvGram(V))
  st R reduces A,d holds d in TS(FrEnvGram(V))
proof
  let A be FrEnvTerm of V;
  let d be object;
  let R be Relation of TS(FrEnvGram(V));
  assume A1: R reduces A,d;
  per cases;
  suppose A = d;
    hence thesis;
  end;
  suppose A <> d;
    then d in field R by A1,REWRITE1:18;
    then A2: d in (dom R) \/ (rng R) by RELAT_1:def 6;
    per cases by A2,XBOOLE_0:def 3;
    suppose d in dom R;
      then consider y being object such that
      B1: [d,y] in R by XTUPLE_0:def 12;
      R c= [:TS(FrEnvGram(V)), TS(FrEnvGram(V)):];
      then [d,y] in [:TS(FrEnvGram(V)), TS(FrEnvGram(V)):] by B1;
      hence thesis by ZFMISC_1:87;
    end;
    suppose d in rng R;
      then consider y being object such that
      B1: [y,d] in R by XTUPLE_0:def 13;
      R c= [:TS(FrEnvGram(V)), TS(FrEnvGram(V)):];
      then [y,d] in [:TS(FrEnvGram(V)), TS(FrEnvGram(V)):] by B1;
      hence thesis by ZFMISC_1:87;
    end;
  end;
end;

theorem Th8:
  for V being non empty set holds FrRed(V) is confluent
proof
  let V be non empty set;
  set G = FrEnvGram(V);
  let a,b be object;
  assume a,b are_divergent_wrt FrRed(V);
  then consider c being object such that
  A1: FrRed(V) reduces c,a & FrRed(V) reduces c,b by REWRITE1:def 8;
  per cases;
  suppose B0: c in TS G;
    reconsider c1 = c as FrEnvTerm of V by B0;
    B0a: FrRed(V) reduces c1,a & FrRed(V) reduces c1,b by A1;
    a in TS G by B0a,Th7;
    then reconsider a1 = a as FrEnvTerm of V;
    b in TS G by B0a,Th7;
    then reconsider b1 = b as FrEnvTerm of V;
    B1: FrRed(V) reduces c1,a1 & FrRed(V) reduces c1,b1 by A1;
    consider N being FrEnvTerm of V such that
    B2: FrRed(V) reduces a1,N & FrRed(V) reduces b1,N by B1,Th6;
    thus thesis by B2,REWRITE1:def 7;
  end;
  suppose B0: not c in TS G;
    B1: not c in field FrRed(V)
    proof
      assume c in field FrRed(V);
      then C1: c in (dom FrRed(V)) \/ (rng FrRed(V)) by RELAT_1:def 6;
      per cases by C1,XBOOLE_0:def 3;
      suppose c in dom FrRed(V);
        then consider y being object such that
        D1: [c,y] in FrRed(V) by XTUPLE_0:def 12;
        FrRed(V) c= [:TS G, TS G:];
        then [c,y] in [:TS G, TS G:] by D1;
        hence contradiction by B0,ZFMISC_1:87;
      end;
      suppose c in rng FrRed(V);
        then consider y being object such that
        D1: [y,c] in FrRed(V) by XTUPLE_0:def 13;
        FrRed(V) c= [:TS G, TS G:];
        then [y,c] in [:TS G, TS G:] by D1;
        hence contradiction by B0,ZFMISC_1:87;
      end;
    end;
    B2: c = a & c = b by A1,B1,REWRITE1:14;
    FrRed(V) reduces a,a by REWRITE1:12;
    hence thesis by B2,REWRITE1:def 7;
  end;
end;
