:: The translation simulates beta-sigma reduction

environ

 vocabularies NUMBERS, XBOOLE_0, SUBSET_1, TARSKI, ZFMISC_1, FINSEQ_1,
      RELAT_1, FUNCT_1, ORDINAL1, CARD_1, ARYTM_3, XXREAL_0, NAT_1, TREES_1,
      TREES_2, TREES_3, TREES_4, LANG1, STRUCT_0, DTCONSTR, MCART_1, XTUPLE_0,
      FINSET_1, TDGROUP, FUNCOP_1, ARYTM_1, FUNCT_7, XREAL_0, XCMPLX_0,
      REWRITE1, PBOOLE, ENVSYN, ENVLEN, ENVBETA, FRENV_1, FRENV_2, FRENV_3,
      ENVCC, ENVSIG;
 notations TARSKI, XBOOLE_0, ZFMISC_1, SUBSET_1, ORDINAL1, NUMBERS, XCMPLX_0,
      XXREAL_0, NAT_1, RELAT_1, RELSET_1, FUNCT_1, FUNCT_2, FINSEQ_1,
      FINSEQ_2, MCART_1, XTUPLE_0, DOMAIN_1, STRUCT_0, LANG1, TREES_1,
      TREES_2, TREES_3, TREES_4, DTCONSTR, FUNCOP_1, XREAL_0, PBOOLE,
      REWRITE1, ENVSYN, ENVLEN, ENVBETA, FRENV_1, FRENV_2, FRENV_3, ENVCC,
      ENVSIG;
 constructors NUMBERS, XCMPLX_0, XXREAL_0, NAT_1, RELSET_1, FUNCT_2, FINSEQ_1,
      FINSEQ_2, MCART_1, XTUPLE_0, DOMAIN_1, STRUCT_0, LANG1, TREES_1,
      TREES_2, TREES_3, TREES_4, DTCONSTR, PARTFUN1, BINOP_1, SETWISEO,
      XREAL_0, FUNCOP_1, SUBSET_1, CARD_3, FINSEQOP, FINSEQ_4, FINSOP_1,
      PRE_POLY, FUNCT_1, RELAT_1, PBOOLE, REWRITE1, ENVSYN, ENVLEN, ENVBETA,
      FRENV_1, FRENV_2, FRENV_3, ENVCC, ENVSIG;
 registrations XBOOLE_0, SUBSET_1, RELAT_1, FUNCT_1, ORDINAL1, XREAL_0, NAT_1,
      FINSEQ_1, FINSEQ_2, FINSET_1, CARD_1, STRUCT_0, LANG1, TREES_1, TREES_2,
      TREES_3, TREES_4, DTCONSTR, XTUPLE_0, VALUED_0, FUNCOP_1, XCMPLX_0,
      XXREAL_0, NUMBERS, MEMBERED, PBOOLE, REWRITE1, ENVSYN, ENVPEAK,
      FRENV_1, FRENV_3, ENVSIG;
 requirements NUMERALS, REAL, BOOLE, SUBSET, ARITHM;
 definitions TARSKI, XBOOLE_0, DTCONSTR, TREES_3, TREES_4, RELAT_1, FUNCT_1,
      FINSEQ_1, FUNCOP_1, SUBSET_1, REWRITE1, ENVSYN, ENVLEN, ENVBETA, ENVCC;
 theorems TARSKI, XBOOLE_0, ZFMISC_1, XTUPLE_0, REWRITE1, ENVSYN, ENVLEN,
      ENVBETA, ENVSIG, FRENV_1, FRENV_2, FRENV_3, ENVCC;
 schemes ENVKEY;
begin :: Translating the identity environment

reserve V for non empty set;

theorem Th1:
  tr (eId V) = fId V
proof
  set v = the Element of V;
  tr (eVar v) = fVar v & tr (eId V) = fId V by FRENV_3:8;
  hence thesis;
end;

begin :: Simulation

theorem Th2:
  for M,N being EnvEpsTerm of V st [M,N] in BetaSigmaRed(V)
  holds FrRed(V) reduces tr M, tr N
proof
  let M,N be EnvEpsTerm of V;
  set G = EnvEpsGram(V);
  set Q = { z where z is Element of [:TS G, TS G:] :
    ex A,B being EnvEpsTerm of V st z = [A,B] &
      FrRed(V) reduces tr A, tr B };
  A1: Q c= [:TS G, TS G:]
  proof
    let u be object;
    assume u in Q;
    then ex z being Element of [:TS G, TS G:] st u = z &
      ex A,B being EnvEpsTerm of V st z = [A,B] &
        FrRed(V) reduces tr A, tr B;
    hence thesis;
  end;
  reconsider Q1 = Q as Relation of TS G by A1;
  A2: for a,b being EnvEpsTerm of V holds
    ( [a,b] in Q1 iff FrRed(V) reduces tr a, tr b )
  proof
    let a,b be EnvEpsTerm of V;
    hereby
      assume [a,b] in Q1;
      then consider z being Element of [:TS G, TS G:] such that
      B1: [a,b] = z and
      B2: ex A,B being EnvEpsTerm of V st z = [A,B] &
        FrRed(V) reduces tr A, tr B;
      consider A,B being EnvEpsTerm of V such that
      B3: z = [A,B] & FrRed(V) reduces tr A, tr B by B2;
      a = A & b = B by B1,B3,XTUPLE_0:1;
      hence FrRed(V) reduces tr a, tr b by B3;
    end;
    assume C1: FrRed(V) reduces tr a, tr b;
    C2: [a,b] in [:TS G, TS G:] by ZFMISC_1:87;
    then reconsider z = [a,b] as Element of [:TS G, TS G:];
    ex A,B being EnvEpsTerm of V st z = [A,B] &
      FrRed(V) reduces tr A, tr B by C1;
    hence thesis;
  end;
  AL: for A,B being EnvEpsTerm of V st [tr A, tr B] in FrRed(V)
    holds [A,B] in Q1
  proof
    let A,B be EnvEpsTerm of V;
    assume [tr A, tr B] in FrRed(V);
    then FrRed(V) reduces tr A, tr B by REWRITE1:15;
    hence thesis by A2;
  end;
  AC: for A,B being EnvEpsTerm of V holds
    tr (A (o) B) = fApp(fEps (tr A), tr B) by FRENV_3:13;
  D1: for A,B being EnvEpsTerm of V, x being Element of V holds
      [eLam(x,A) (@) B, A (o) eExt(B,x,eId V)] in Q1
    proof
      let A,B be EnvEpsTerm of V, x be Element of V;
      B1: tr (eLam(x,A) (@) B) = fApp(tr (eLam(x,A)), tr B) by FRENV_3:11
        .= fApp(fLam(x, tr A), tr B) by FRENV_3:9;
      B2: tr (A (o) eExt(B,x,eId V))
          = fApp(fEps (tr A), tr (eExt(B,x,eId V))) by AC
        .= fApp(fEps (tr A), fExt(tr B, x, tr (eId V))) by FRENV_3:12
        .= fApp(fEps (tr A), fExt(tr B, x, fId V)) by Th1;
      [fApp(fLam(x, tr A), tr B),
        fApp(fEps (tr A), fExt(tr B, x, fId V))] in FrRed(V) by FRENV_2:4;
      hence thesis by AL,B1,B2;
    end;
  D2: for A,B,L being EnvEpsTerm of V, x being Element of V holds
      [(eLam(x,A) (o) L) (@) B, A (o) eExt(B,x,L)] in Q1
    proof
      let A,B,L be EnvEpsTerm of V, x be Element of V;
      B1: tr ((eLam(x,A) (o) L) (@) B)
          = fApp(tr (eLam(x,A) (o) L), tr B) by FRENV_3:11
        .= fApp(fApp(fEps (tr (eLam(x,A))), tr L), tr B) by AC
        .= fApp(fApp(fEps (fLam(x, tr A)), tr L), tr B) by FRENV_3:9;
      B2: tr (A (o) eExt(B,x,L)) = fApp(fEps (tr A), tr (eExt(B,x,L)))
          by AC
        .= fApp(fEps (tr A), fExt(tr B, x, tr L)) by FRENV_3:12;
      [fApp(fApp(fEps (fLam(x, tr A)), tr L), tr B),
        fApp(fEps (tr A), fExt(tr B, x, tr L))] in FrRed(V) by FRENV_2:5;
      hence thesis by AL,B1,B2;
    end;
  D3: for A,B being EnvEpsTerm of V holds
      [(eEps A) (@) B, A (o) B] in Q1
    proof
      let A,B be EnvEpsTerm of V;
      B1: tr ((eEps A) (@) B) = fApp(tr (eEps A), tr B) by FRENV_3:11
        .= fApp(fEps (tr A), tr B) by FRENV_3:10;
      B2: tr (A (o) B) = fApp(fEps (tr A), tr B) by AC;
      FrRed(V) reduces tr ((eEps A) (@) B), tr (A (o) B) by B1,B2,
        REWRITE1:12;
      hence thesis by A2;
    end;
  D4: for A,B,L being EnvEpsTerm of V holds
      [(A (o) B) (o) L, A (o) (B (o) L)] in Q1
    proof
      let A,B,L be EnvEpsTerm of V;
      B1: tr ((A (o) B) (o) L)
          = fApp(fEps (tr (A (o) B)), tr L) by AC
        .= fApp(fEps (fApp(fEps (tr A), tr B)), tr L) by AC;
      B2: tr (A (o) (B (o) L)) = fApp(fEps (tr A), tr (B (o) L)) by AC
        .= fApp(fEps (tr A), fApp(fEps (tr B), tr L)) by AC;
      [fApp(fEps (fApp(fEps (tr A), tr B)), tr L),
        fApp(fEps (tr A), fApp(fEps (tr B), tr L))] in FrRed(V) by FRENV_2:7;
      hence thesis by AL,B1,B2;
    end;
  D5: for A being EnvEpsTerm of V holds [(eId V) (o) A, A] in Q1
    proof
      let A be EnvEpsTerm of V;
      B1: tr ((eId V) (o) A) = fApp(fEps (tr (eId V)), tr A) by AC
        .= fApp(fEps (fId V), tr A) by Th1;
      [fApp(fEps (fId V), tr A), tr A] in FrRed(V) by FRENV_2:8;
      hence thesis by AL,B1;
    end;
  D6: for A being EnvEpsTerm of V holds [A (o) (eId V), A] in Q1
    proof
      let A be EnvEpsTerm of V;
      B1: tr (A (o) (eId V)) = fApp(fEps (tr A), tr (eId V)) by AC
        .= fApp(fEps (tr A), fId V) by Th1;
      [fApp(fEps (tr A), fId V), tr A] in FrRed(V) by FRENV_2:9;
      hence thesis by AL,B1;
    end;
  D7: for L,A,B being EnvEpsTerm of V, x being Element of V holds
      [eExt(L,x,A) (o) B, eExt(L (o) B,x,A (o) B)] in Q1
    proof
      let L,A,B be EnvEpsTerm of V, x be Element of V;
      B1: tr (eExt(L,x,A) (o) B)
          = fApp(fEps (tr (eExt(L,x,A))), tr B) by AC
        .= fApp(fEps (fExt(tr L, x, tr A)), tr B) by FRENV_3:12;
      B2: tr (eExt(L (o) B,x,A (o) B))
          = fExt(tr (L (o) B), x, tr (A (o) B)) by FRENV_3:12
        .= fExt(fApp(fEps (tr L), tr B), x, tr (A (o) B)) by AC
        .= fExt(fApp(fEps (tr L), tr B), x, fApp(fEps (tr A), tr B)) by AC;
      [fApp(fEps (fExt(tr L, x, tr A)), tr B),
        fExt(fApp(fEps (tr L), tr B), x, fApp(fEps (tr A), tr B))]
        in FrRed(V) by FRENV_2:10;
      hence thesis by AL,B1,B2;
    end;
  D8: for A,B being EnvEpsTerm of V, x being Element of V holds
      [(eVar x) (o) eExt(A,x,B), A] in Q1
    proof
      let A,B be EnvEpsTerm of V, x be Element of V;
      B1: tr ((eVar x) (o) eExt(A,x,B))
          = fApp(fEps (tr (eVar x)), tr (eExt(A,x,B))) by AC
        .= fApp(fEps (fVar x), tr (eExt(A,x,B))) by FRENV_3:8
        .= fApp(fEps (fVar x), fExt(tr A, x, tr B)) by FRENV_3:12;
      [fApp(fEps (fVar x), fExt(tr A, x, tr B)), tr A] in FrRed(V)
        by FRENV_2:11;
      hence thesis by AL,B1;
    end;
  D9: for A,B being EnvEpsTerm of V, x,y being Element of V st x <> y
      holds [(eVar x) (o) eExt(A,y,B), (eVar x) (o) B] in Q1
    proof
      let A,B be EnvEpsTerm of V, x,y be Element of V;
      assume B0: x <> y;
      B1: tr ((eVar x) (o) eExt(A,y,B))
          = fApp(fEps (tr (eVar x)), tr (eExt(A,y,B))) by AC
        .= fApp(fEps (fVar x), tr (eExt(A,y,B))) by FRENV_3:8
        .= fApp(fEps (fVar x), fExt(tr A, y, tr B)) by FRENV_3:12;
      B2: tr ((eVar x) (o) B) = fApp(fEps (tr (eVar x)), tr B) by AC
        .= fApp(fEps (fVar x), tr B) by FRENV_3:8;
      [fApp(fEps (fVar x), fExt(tr A, y, tr B)),
        fApp(fEps (fVar x), tr B)] in FrRed(V) by B0,FRENV_2:12;
      hence thesis by AL,B1,B2;
    end;
  D10: for A,B,L being EnvEpsTerm of V holds
      [(A (@) B) (o) L, (A (o) L) (@) (B (o) L)] in Q1
    proof
      let A,B,L be EnvEpsTerm of V;
      B1: tr ((A (@) B) (o) L) = fApp(fEps (tr (A (@) B)), tr L) by AC
        .= fApp(fEps (fApp(tr A, tr B)), tr L) by FRENV_3:11;
      B2: tr ((A (o) L) (@) (B (o) L))
          = fApp(tr (A (o) L), tr (B (o) L)) by FRENV_3:11
        .= fApp(fApp(fEps (tr A), tr L), tr (B (o) L)) by AC
        .= fApp(fApp(fEps (tr A), tr L), fApp(fEps (tr B), tr L)) by AC;
      [fApp(fEps (fApp(tr A, tr B)), tr L),
        fApp(fApp(fEps (tr A), tr L), fApp(fEps (tr B), tr L))]
        in FrRed(V) by FRENV_2:13;
      hence thesis by AL,B1,B2;
    end;
  D11: for A,B being EnvEpsTerm of V holds [(eEps A) (o) B, eEps A] in Q1
    proof
      let A,B be EnvEpsTerm of V;
      B1: tr ((eEps A) (o) B) = fApp(fEps (tr (eEps A)), tr B) by AC
        .= fApp(fEps (fEps (tr A)), tr B) by FRENV_3:10;
      B2: tr (eEps A) = fEps (tr A) by FRENV_3:10;
      [fApp(fEps (fEps (tr A)), tr B), fEps (tr A)] in FrRed(V)
        by FRENV_2:6;
      hence thesis by AL,B1,B2;
    end;
  A3: Q1 is_cc_over BetaSigmaRoot(V)
  proof
    thus BetaSigmaRoot(V) c= Q1
    proof
      now
        let u be object;
        assume B0: u in BetaSigmaRoot(V);
        BetaSigmaRoot(V) c= [:TS G, TS G:];
        then u in [:TS G, TS G:] by B0;
        then consider a,b being object such that
        B1: a in TS G & b in TS G & u = [a,b] by ZFMISC_1:84;
        reconsider P = a, S = b as EnvEpsTerm of V by B1;
        B2: [P,S] in BetaSigmaRoot(V) by B0,B1;
        BetaSigmaRoot(V) = BetaRoot(V) \/ SigmaRoot(V) by ENVBETA:def 3;
        then B3: [P,S] in BetaRoot(V) or [P,S] in SigmaRoot(V)
          by B2,XBOOLE_0:def 3;
        B4: [P,S] in Q1
        proof
          per cases by B3,ENVBETA:1,ENVSIG:1;
          suppose ex A,B being EnvEpsTerm of V, x being Element of V st P =
            eLam(x,A) (@) B & S = A (o) eExt(B,x,eId V);
            then consider A,B being EnvEpsTerm of V, x being Element of V
              such that
            C1: P = eLam(x,A) (@) B & S = A (o) eExt(B,x,eId V);
            thus thesis by C1,D1;
          end;
          suppose ex A,B,L being EnvEpsTerm of V, x being Element of V st P
            = (eLam(x,A) (o) L) (@) B & S = A (o) eExt(B,x,L);
            then consider A,B,L being EnvEpsTerm of V, x being Element of V
              such that
            C1: P = (eLam(x,A) (o) L) (@) B & S = A (o) eExt(B,x,L);
            thus thesis by C1,D2;
          end;
          suppose ex A,B being EnvEpsTerm of V st P = (eEps A) (@) B & S =
            A (o) B;
            then consider A,B being EnvEpsTerm of V such that
            C1: P = (eEps A) (@) B & S = A (o) B;
            thus thesis by C1,D3;
          end;
          suppose ex A,B,L being EnvEpsTerm of V st P = (A (o) B) (o) L
            & S = A (o) (B (o) L);
            then consider A,B,L being EnvEpsTerm of V such that
            C1: P = (A (o) B) (o) L & S = A (o) (B (o) L);
            thus thesis by C1,D4;
          end;
          suppose ex A being EnvEpsTerm of V st P = (eId V) (o) A & S = A;
            then consider A being EnvEpsTerm of V such that
            C1: P = (eId V) (o) A & S = A;
            thus thesis by C1,D5;
          end;
          suppose ex A being EnvEpsTerm of V st P = A (o) (eId V) & S = A;
            then consider A being EnvEpsTerm of V such that
            C1: P = A (o) (eId V) & S = A;
            thus thesis by C1,D6;
          end;
          suppose ex L,A,B being EnvEpsTerm of V, x being Element of V st P
            = eExt(L,x,A) (o) B & S = eExt(L (o) B,x,A (o) B);
            then consider L,A,B being EnvEpsTerm of V, x being Element of V
              such that
            C1: P = eExt(L,x,A) (o) B & S =
              eExt(L (o) B,x,A (o) B);
            thus thesis by C1,D7;
          end;
          suppose ex A,B being EnvEpsTerm of V, x being Element of V st P =
            (eVar x) (o) eExt(A,x,B) & S = A;
            then consider A,B being EnvEpsTerm of V, x being Element of V
              such that
            C1: P = (eVar x) (o) eExt(A,x,B) & S = A;
            thus thesis by C1,D8;
          end;
          suppose ex A,B being EnvEpsTerm of V, x,y being Element of V st x
            <> y & P = (eVar x) (o) eExt(A,y,B) & S = (eVar x) (o) B;
            then consider A,B being EnvEpsTerm of V, x,y being Element of V
              such that
            C1: x <> y & P = (eVar x) (o) eExt(A,y,B) & S = (eVar x) (o) B;
            thus thesis by C1,D9;
          end;
          suppose ex A,B,L being EnvEpsTerm of V st P = (A (@) B) (o) L &
            S = (A (o) L) (@) (B (o) L);
            then consider A,B,L being EnvEpsTerm of V such that
            C1: P = (A (@) B) (o) L & S = (A (o) L) (@) (B (o) L);
            thus thesis by C1,D10;
          end;
          suppose ex A,B being EnvEpsTerm of V st P = (eEps A) (o) B & S =
            eEps A;
            then consider A,B being EnvEpsTerm of V such that
            C1: P = (eEps A) (o) B & S = eEps A;
            thus thesis by C1,D11;
          end;
        end;
        thus u in Q1 by B1,B4;
      end;
      hence thesis by TARSKI:def 3;
    end;
    thus for A,A1,B being EnvEpsTerm of V st [A,A1] in Q1 holds
      [A (@) B, A1 (@) B] in Q1
    proof
      let A,A1,B be EnvEpsTerm of V;
      assume [A,A1] in Q1;
      then C0: FrRed(V) reduces tr A, tr A1 by A2;
      C1: tr (A (@) B) = fApp(tr A, tr B) by FRENV_3:11;
      C2: tr (A1 (@) B) = fApp(tr A1, tr B) by FRENV_3:11;
      FrRed(V) reduces fApp(tr A, tr B), fApp(tr A1, tr B) by C0,FRENV_2:20;
      hence thesis by A2,C1,C2;
    end;
    thus for A,B,B1 being EnvEpsTerm of V st [B,B1] in Q1 holds
      [A (@) B, A (@) B1] in Q1
    proof
      let A,B,B1 be EnvEpsTerm of V;
      assume [B,B1] in Q1;
      then C0: FrRed(V) reduces tr B, tr B1 by A2;
      C1: tr (A (@) B) = fApp(tr A, tr B) by FRENV_3:11;
      C2: tr (A (@) B1) = fApp(tr A, tr B1) by FRENV_3:11;
      FrRed(V) reduces fApp(tr A, tr B), fApp(tr A, tr B1) by C0,FRENV_2:21;
      hence thesis by A2,C1,C2;
    end;
    thus for A,A1 being EnvEpsTerm of V, x being Element of V st [A,A1] in Q1
      holds [eLam(x,A), eLam(x,A1)] in Q1
    proof
      let A,A1 be EnvEpsTerm of V, x be Element of V;
      assume [A,A1] in Q1;
      then C0: FrRed(V) reduces tr A, tr A1 by A2;
      C1: tr (eLam(x,A)) = fLam(x, tr A) by FRENV_3:9;
      C2: tr (eLam(x,A1)) = fLam(x, tr A1) by FRENV_3:9;
      FrRed(V) reduces fLam(x, tr A), fLam(x, tr A1) by C0,FRENV_2:22;
      hence thesis by A2,C1,C2;
    end;
    thus for A,A1,B being EnvEpsTerm of V, x being Element of V
      st [A,A1] in Q1 holds [eExt(A,x,B), eExt(A1,x,B)] in Q1
    proof
      let A,A1,B be EnvEpsTerm of V, x be Element of V;
      assume [A,A1] in Q1;
      then C0: FrRed(V) reduces tr A, tr A1 by A2;
      C1: tr (eExt(A,x,B)) = fExt(tr A, x, tr B) by FRENV_3:12;
      C2: tr (eExt(A1,x,B)) = fExt(tr A1, x, tr B) by FRENV_3:12;
      FrRed(V) reduces fExt(tr A, x, tr B), fExt(tr A1, x, tr B)
        by C0,FRENV_2:23;
      hence thesis by A2,C1,C2;
    end;
    thus for A,B,B1 being EnvEpsTerm of V, x being Element of V
      st [B,B1] in Q1 holds [eExt(A,x,B), eExt(A,x,B1)] in Q1
    proof
      let A,B,B1 be EnvEpsTerm of V, x be Element of V;
      assume [B,B1] in Q1;
      then C0: FrRed(V) reduces tr B, tr B1 by A2;
      C1: tr (eExt(A,x,B)) = fExt(tr A, x, tr B) by FRENV_3:12;
      C2: tr (eExt(A,x,B1)) = fExt(tr A, x, tr B1) by FRENV_3:12;
      FrRed(V) reduces fExt(tr A, x, tr B), fExt(tr A, x, tr B1)
        by C0,FRENV_2:24;
      hence thesis by A2,C1,C2;
    end;
    thus for A,A1,B being EnvEpsTerm of V st [A,A1] in Q1 holds
      [A (o) B, A1 (o) B] in Q1
    proof
      let A,A1,B be EnvEpsTerm of V;
      assume [A,A1] in Q1;
      then C0: FrRed(V) reduces tr A, tr A1 by A2;
      C1: tr (A (o) B) = fApp(fEps (tr A), tr B) by AC;
      C2: tr (A1 (o) B) = fApp(fEps (tr A1), tr B) by AC;
      FrRed(V) reduces fEps (tr A), fEps (tr A1) by C0,FRENV_2:25;
      then FrRed(V) reduces fApp(fEps (tr A), tr B), fApp(fEps (tr A1), tr B)
        by FRENV_2:20;
      hence thesis by A2,C1,C2;
    end;
    thus for A,B,B1 being EnvEpsTerm of V st [B,B1] in Q1 holds
      [A (o) B, A (o) B1] in Q1
    proof
      let A,B,B1 be EnvEpsTerm of V;
      assume [B,B1] in Q1;
      then C0: FrRed(V) reduces tr B, tr B1 by A2;
      C1: tr (A (o) B) = fApp(fEps (tr A), tr B) by AC;
      C2: tr (A (o) B1) = fApp(fEps (tr A), tr B1) by AC;
      FrRed(V) reduces fApp(fEps (tr A), tr B), fApp(fEps (tr A), tr B1)
        by C0,FRENV_2:21;
      hence thesis by A2,C1,C2;
    end;
    thus for A,A1 being EnvEpsTerm of V st [A,A1] in Q1 holds
      [eEps A, eEps A1] in Q1
    proof
      let A,A1 be EnvEpsTerm of V;
      assume [A,A1] in Q1;
      then C0: FrRed(V) reduces tr A, tr A1 by A2;
      C1: tr (eEps A) = fEps (tr A) by FRENV_3:10;
      C2: tr (eEps A1) = fEps (tr A1) by FRENV_3:10;
      FrRed(V) reduces fEps (tr A), fEps (tr A1) by C0,FRENV_2:25;
      hence thesis by A2,C1,C2;
    end;
  end;
  CC BetaSigmaRoot(V) c= Q1 by A3,ENVCC:2;
  then A5: BetaSigmaRed(V) c= Q1 by ENVBETA:def 4;
  assume A7: [M,N] in BetaSigmaRed(V);
  then [M,N] in Q1 by A5;
  hence thesis by A2;
end;

theorem Th3:
  for M,N being EnvEpsTerm of V st BetaSigmaRed(V) reduces M,N
  holds FrRed(V) reduces tr M, tr N
proof
  let M,N be EnvEpsTerm of V;
  set G = EnvEpsGram(V);
  assume A3: BetaSigmaRed(V) reduces M,N;
  defpred P[object] means ex A being EnvEpsTerm of V st A = $1 &
    FrRed(V) reduces tr M, tr A;
  A4: for a,b being object st P[a] & [a,b] in BetaSigmaRed(V) holds P[b]
  proof
    let a,b be object;
    assume that B1: P[a] and B2: [a,b] in BetaSigmaRed(V);
    consider A being EnvEpsTerm of V such that
    B3: A = a & FrRed(V) reduces tr M, tr A by B1;
    BetaSigmaRed(V) c= [:TS G, TS G:];
    then [a,b] in [:TS G, TS G:] by B2;
    then b in TS G by ZFMISC_1:87;
    then reconsider b1 = b as EnvEpsTerm of V;
    [A,b1] in BetaSigmaRed(V) by B2,B3;
    then FrRed(V) reduces tr A, tr b1 by Th2;
    then FrRed(V) reduces tr M, tr b1 by B3,REWRITE1:16;
    hence thesis;
  end;
  A5: for a,b being object st BetaSigmaRed(V) reduces a,b & P[a] holds P[b]
    from ENVKEY:sch 1(A4);
  FrRed(V) reduces tr M, tr M by REWRITE1:12;
  then P[M];
  then P[N] by A3,A5;
  then consider A being EnvEpsTerm of V such that
  A6: A = N & FrRed(V) reduces tr M, tr A;
  thus thesis by A6;
end;
