import Init

/-!
# λ_FREnv: syntax and beta-sigma reduction

This file formalizes, from the specification documents
`docs/frenv-syntax.md` and `docs/frenv-reduction-beta-sigma.md`:

* the syntax `Trm V C` of λ_FREnv,
* the one-step beta-sigma reduction `BetaSigmaStep`,
* its reflexive-transitive closure `BetaSigmaSteps`,
* the generic confluence infrastructure used by the main proof.

The calculus uses two primitive sets: variables `V` and constants `C`.
No substitution operation and no binding machinery are introduced: the
formalization follows the specification exactly.
-/

namespace LambdaFrenv

universe u v

/-- Terms of λ_FREnv over variables `V` and constants `C`.

Correspondence with the specification grammar
`M, N, L ::= c | x | λx.M | M N | id | (M/x)·N | ε(M)`:

* `Trm.const c`   ↔ `c`
* `Trm.var x`     ↔ `x`
* `Trm.lam x M`   ↔ `λx.M`
* `Trm.app M N`   ↔ `M N`
* `Trm.id`        ↔ `id`
* `Trm.ext M x N` ↔ `(M/x)·N`
* `Trm.eps M`     ↔ `ε(M)`
-/
inductive Trm (V : Type u) (C : Type v) where
  | var : V → Trm V C
  | const : C → Trm V C
  | lam : V → Trm V C → Trm V C
  | app : Trm V C → Trm V C → Trm V C
  | id : Trm V C
  | ext : Trm V C → V → Trm V C → Trm V C
  | eps : Trm V C → Trm V C
  deriving DecidableEq

/-- The reflexive-transitive closure of a relation `r : α → α → Prop`.

Core Lean does not ship a reflexive-transitive closure in its base library,
so this file defines the standard one (reflexive closure generated by
`tail`-append), which is exactly the mathematical relation
`M →* N` for the step relation `r`.
-/
inductive ReflTransGen {α : Type u} (r : α → α → Prop) : α → α → Prop where
  | refl : ReflTransGen r a a
  | tail : ReflTransGen r a b → r b c → ReflTransGen r a c

namespace ReflTransGen

/-- Transitivity of the reflexive-transitive closure. -/
theorem trans {α : Type u} {r : α → α → Prop} {a b c : α}
    (h₁ : ReflTransGen r a b) (h₂ : ReflTransGen r b c) : ReflTransGen r a c := by
  revert a
  induction h₂ with
  | refl =>
      intro a h
      exact h
  | tail h' hstep ih =>
      intro a h
      exact ReflTransGen.tail (ih h) hstep

/-- A single step is a multi-step. -/
theorem single {α : Type u} {r : α → α → Prop} {a b : α}
    (h : r a b) : ReflTransGen r a b :=
  ReflTransGen.tail ReflTransGen.refl h

end ReflTransGen

/-- One-step beta-sigma reduction of λ_FREnv, as specified in
`docs/frenv-reduction-beta-sigma.md`.

The eleven root rules are `beta`, `betaClos`, `stab`, `assoc`, `idL`, `idR`,
`dExt`, `varRef`, `varSkip`, `dApp`, `const`; the six compatibility rules are
`appL`, `appR`, `lam`, `extL`, `extR`, `envAbst`.
-/
inductive BetaSigmaStep : Trm V C → Trm V C → Prop where
  -- Beta: ((λx.M)N) → (ε(M)((N/x)·id))
  | beta :
      BetaSigmaStep (Trm.app (Trm.lam x M) N) (Trm.app (Trm.eps M) (Trm.ext N x Trm.id))
  -- BetaClos: ((ε(λx.M)L)N) → (ε(M)((N/x)·L))
  | betaClos :
      BetaSigmaStep (Trm.app (Trm.app (Trm.eps (Trm.lam x M)) L) N)
        (Trm.app (Trm.eps M) (Trm.ext N x L))
  -- Stab: (ε(ε(M))N) → ε(M)
  | stab :
      BetaSigmaStep (Trm.app (Trm.eps (Trm.eps M)) N) (Trm.eps M)
  -- Assoc: ε((ε(L)M))N → ε(L)(ε(M)N)
  | assoc :
      BetaSigmaStep (Trm.app (Trm.eps (Trm.app (Trm.eps L) M)) N)
        (Trm.app (Trm.eps L) (Trm.app (Trm.eps M) N))
  -- IdL: (ε(id)M) → M
  | idL :
      BetaSigmaStep (Trm.app (Trm.eps Trm.id) M) M
  -- IdR: (ε(M)id) → M
  | idR :
      BetaSigmaStep (Trm.app (Trm.eps M) Trm.id) M
  -- DExtn: (ε((L/x)·M)N) → ((ε(L)N)/x)·(ε(M)N)
  | dExt :
      BetaSigmaStep (Trm.app (Trm.eps (Trm.ext L x M)) N)
        (Trm.ext (Trm.app (Trm.eps L) N) x (Trm.app (Trm.eps M) N))
  -- VarRef: (ε(x)((M/x)·N)) → M
  | varRef :
      BetaSigmaStep (Trm.app (Trm.eps (Trm.var x)) (Trm.ext M x N)) M
  -- VarSkip: x ≠ y  ⇒  (ε(y)((M/x)·N)) → (ε(y)N)
  | varSkip : x ≠ y →
      BetaSigmaStep (Trm.app (Trm.eps (Trm.var y)) (Trm.ext M x N))
        (Trm.app (Trm.eps (Trm.var y)) N)
  -- DApp: (ε((MN))L) → ((ε(M)L)(ε(N)L))
  | dApp :
      BetaSigmaStep (Trm.app (Trm.eps (Trm.app M N)) L)
        (Trm.app (Trm.app (Trm.eps M) L) (Trm.app (Trm.eps N) L))
  -- Const: ε(c)M → c
  | const :
      BetaSigmaStep (Trm.app (Trm.eps (Trm.const c)) M) (Trm.const c)
  -- AppL: M → N  ⇒  (M L) → (N L)
  | appL : BetaSigmaStep M N →
      BetaSigmaStep (Trm.app M L) (Trm.app N L)
  -- AppR: M → N  ⇒  (L M) → (L N)
  | appR : BetaSigmaStep M N →
      BetaSigmaStep (Trm.app L M) (Trm.app L N)
  -- Lam: M → N  ⇒  λx.M → λx.N
  | lam : BetaSigmaStep M N →
      BetaSigmaStep (Trm.lam x M) (Trm.lam x N)
  -- ExtnL: M → N  ⇒  (M/x)·L → (N/x)·L
  | extL : BetaSigmaStep M N →
      BetaSigmaStep (Trm.ext M x L) (Trm.ext N x L)
  -- ExtnR: M → N  ⇒  (L/x)·M → (L/x)·N
  | extR : BetaSigmaStep M N →
      BetaSigmaStep (Trm.ext L x M) (Trm.ext L x N)
  -- EnvAbst: M → N  ⇒  ε(M) → ε(N)
  | envAbst : BetaSigmaStep M N →
      BetaSigmaStep (Trm.eps M) (Trm.eps N)

/-- The reflexive-transitive closure of `BetaSigmaStep`, i.e. `→βσ*`. -/
abbrev BetaSigmaSteps (M N : Trm V C) : Prop :=
  ReflTransGen BetaSigmaStep M N

/-! ## Confluence infrastructure

Generic definitions over an abstract relation `r : α → α → Prop`.
-/

/-- Strong (one-step) confluence of `r`: two single steps from a common
source admit a common single-step reduct. -/
def StronglyConfluent {α : Type u} (r : α → α → Prop) : Prop :=
  ∀ ⦃M N₁ N₂ : α⦄, r M N₁ → r M N₂ → ∃ N : α, r N₁ N ∧ r N₂ N

/-- Confluence of the reflexive-transitive closure of `r`. -/
def Confluent {α : Type u} (r : α → α → Prop) : Prop :=
  ∀ ⦃M N₁ N₂ : α⦄,
    ReflTransGen r M N₁ → ReflTransGen r M N₂ →
      ∃ N : α, ReflTransGen r N₁ N ∧ ReflTransGen r N₂ N

/-- Multi-step joinability under `r`. -/
def Joinable {α : Type u} (r : α → α → Prop) (M N : α) : Prop :=
  ∃ L : α, ReflTransGen r M L ∧ ReflTransGen r N L

end LambdaFrenv
